### PR TITLE
changed table name for tagging rule

### PR DESCRIPTION
**Pull request by nicosomb**
ping @K-Phoen

### CODE REVIEW

**Comment by j0k3r** [comment]
What was the generated name before that change?

**Comment by nicosomb** [comment]
`wallabag_TaggingRule`

**Comment by j0k3r** [comment]
What is the generated name for the tag user table? Is it `tag_user`? If yes, we should name that table `tagging_rule` instead.

**Comment by nicosomb** [comment]
`wallabag_tag`, `wallabag_entry_tag`, etc.

You're right, I fix it.

**Pull request merged**
