### PR TITLE
Make dev/install/update script posix compatible

### LINKED ISSUE #3571: update.sh uses BASH_SOURCE to determine directory
### Issue details

In [update.sh in line 10 ](https://github.com/wallabag/wallabag/blob/master/scripts/update.sh#L10) we use BASH_SOURCE to try to find the directory of update.sh script:

```bash
DIR="${BASH_SOURCE}"
```

But according to documentation, this variable is an array.

> BASH_SOURCE
>
>    An array variable whose members are the source filenames where the corresponding shell function names in the FUNCNAME array variable are defined. The shell function ${FUNCNAME[$i]} is defined in the file ${BASH_SOURCE[$i]} and called from ${BASH_SOURCE[$i+1]}

https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html#index-BASH_005fSOURCE

If we want to find the directory of the update.sh script, we should follow a different approach, e.g.:

```bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
```

https://stackoverflow.com/a/246128/709697

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.2
* How did you install wallabag? Via `git clone` or by downloading the package?git
* Last wallabag version that did not exhibit the issue (if applicable):2.3.1
* php version:
* OS:debian
* type of hosting (shared or dedicated):dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL):postgresql

### PR DESCRIPTION
**Pull request by baurmatt**
Fixes #3571.

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| CHANGELOG.md  | no
| License       | MIT

### CODE REVIEW

**Comment by kissgyorgy** [comment]
$0 in bash is the name of the script itself. It has nothing to do with a directory.
See: https://www.tldp.org/LDP/abs/html/othertypesv.html

**Comment by techexo** [comment]
We could go for something like `dirname $0`, but I don't know if `dirname` is included by default in all distributions.
It seems that `"$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"` is the common way to do it in Bash.

**Comment by techexo** [comment]
@baurmatt It seems that you're right! 

But I don't understand why `${BASH_SOURCE}` in update.sh is considered as being the `DIR`, as it returns the name of the script (and if necessary the relative path to go to it). 
The `if [ ! -d "$DIR" ]; then DIR="$PWD/scripts"; fi` instruction should always be true, shouldn't it ? (In the sense that we're basically looking if the script file is a directory...)

**Comment by techexo** [comment]
I mean, do we even _need_ that? If I'm not mistaken, this is just to differentiate between when the scripts are launched from the `scripts` directory and when they are launched from the `GNUMakefile`. Why not say that everything is launched from the makefile (as I reckon it should) and don't bother with this?

**Comment by baurmatt** [comment]
Not sure why this behavior was implemented. Perhaps people starting the update script from outside of the docroot.

**Comment by j0k3r** [comment]
@techexo this seems to be a better solution than try to handle all compatibility.
I think we can remove that check and just have `. "scripts/require.sh"`

Maybe we should add a check if that file exist and if not, exit and ask to use makefile instead.

I guess it was defined like when people launch sh file from the scripts folder directly.

**Comment by baurmatt** [comment]
Thanks everyone! I've updated the PR as suggested by @j0k3r .

**Comment by j0k3r** [comment]
@Kdecherf are you ok with these changes?

**Pull request merged**
