### PR TITLE
🎨 Changed visibility for article stats

### PR DESCRIPTION
**Pull request by nicosomb**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| CHANGELOG.md  | no
| License       | MIT

Before 

Capture d’écran 2020-04-21 à 18 06 37

After 

Capture d’écran 2020-04-21 à 18 21 30

### CODE REVIEW

**Comment by Simounet** [comment]
I'm not a huge fan of the color switching to grey. wallabag is quite soft and I think these touch of color bump up the design.

**Comment by nicosomb** [comment]
In fact, it allows the user to be focused on the article content.

**Comment by j0k3r** [comment]
I like it

**Comment by nicosomb** [comment]
Just give me your thumb :)

**Pull request merged**
