### PR TITLE
Add Cloudron as installation method

### PR DESCRIPTION
**Pull request by nebulade**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | n/a
| Documentation | yes
| Translation   | no
| License       | MIT

Thanks for the great app and especially the latest continued effort into making it better and better.
I have packaged wallabag for Cloudron and this pull request would add it to the docs. Please let me know if this is not applicable. First time for me to use .rst files.

### CODE REVIEW

**Comment by tcitworld** [comment]
Looks good.
Ping @wallabag/translators

**Comment by j0k3r** [comment]
Are you going to keep that version up to date with wallabag releases in the future?

**Comment by nebulade** [comment]
@j0k3r yes that is our intention. Forgot to mention the app package repo is at https://git.cloudron.io/cloudron/wallabag-app/

I also added basic selenium tests to ensure app lifecycle (restore from backup, update, ...) is ok. So usually we have a small time window until we update apps.

**Comment by tcitworld** [comment]
> I also added basic selenium tests to ensure app lifecycle (restore from backup, update, ...) is ok. So usually we have a small time window until we update apps.

Very nice, we could use that.

**Comment by matteocoder** [comment]
```
+Installazione su Cloudron
 +~~~~~~~~~~~~~~~~~~~~~~~~
 +
 +Cloudron fornisce un modo facile di installare webapps sul vostro server focalizzato all\'automazione per  sysadmin ed a mantenere le app aggiornate.
 +wallabag é pacchettizzata come app Cloudron ed é disponibile all\'installazione direttamente dallo store.
 +
 +`Installa wallabag sul tuo Cloudron <https://cloudron.io/store/org.wallabag.cloudronapp.html>`__
+
```
@nebulade can you please explain what do you mean by sysadmin automation? I feel like I didn't translate it too well.

**Comment by nebulade** [comment]
Of course, I was referring typical system administrator tasks like ensuring backups, setting up domains and SSL certificates, updating apps and migrating the data is needed, making sure the app gets restarted if down, ... 

At Cloudron we try to automate all those tasks away from the user, as we see those having to be done over and over again by everyone selfhosting webapps.

**Comment by matteocoder** [comment]
@nebulade  I see, Thanks! So, could I translate it as "automation of sysadmin tasks "?

**Comment by nebulade** [comment]
Yes that sounds good. Might even make more sense in the English version if that makes it clearer.

**Comment by nebulade** [comment]
Hi,is there any status update on this, or is this blocked by something? Thanks.

**Comment by nicosomb** [comment]
I will commit the :it: and :fr: translation.

**Comment by nicosomb** [comment]
@jlnostr @Strubbl we need your help for :de: please.

**Comment by jlnostr** [comment]
Sorry, I am not able to do it right now. Maybe @Strubbl or @nebulade can translate the docs.

**Comment by nebulade** [comment]
Could have done the German one from the start, sorry for not realizing this oddly :-/

**Comment by nicosomb** [comment]
Thank you @nebulade 👍

**Pull request merged**
