### PR TITLE
Feat/home entries updated

### PR DESCRIPTION
**Pull request by Simounet**
Hi,

I updated the style for the home entries. An overflow issue was bothering me for a long time.
Before:
overflow before

After:
overflow after

Because of that, I needed to extract the mass action list from the list (it wasn't semantical anyway).

mass-action-extracted

And because I was there, I replaced the entries' unordered list by an ordered one.

Have a nice day.

### CODE REVIEW

**Comment by j0k3r** [comment]
Looks like updating the HTML structure broken tests

**Comment by Simounet** [comment]
Ok, I get it and I will fix it.

**Comment by Simounet** [comment]
Fixed it. I'm proposing to use the `data-test` attribute for testing purpose to separate concerns.

**Comment by j0k3r** [comment]
Great! Good idea.
Can you squash?

**Comment by Simounet** [comment]
I can but each of these commits mean something.

**Review by j0k3r — APPROVED** [review]
I'm ok with that!

**Review by nicosomb — APPROVED** [review]

**Pull request merged**
