### PR TITLE
fix #1433: remove www. on entries view

### LINKED ISSUE #1433: When displaying domain on themes, skip the www part
No one cares about it.

### PR DESCRIPTION
**Pull request by nicosomb**
fix #1433

### CODE REVIEW

**Comment by nicosomb** [comment]
Tests are broken, I'm on it.

**Comment by nicosomb** [comment]
mysql tests failed. https://travis-ci.org/wallabag/wallabag/jobs/82819649
ping @j0k3r any idea?

**Comment by nicosomb** [comment]
OK I forgot a file ... @tcitworld you can merge ;-)

**Comment by j0k3r** [comment]
And the unit test on the extension?

**Comment by nicosomb** [comment]
Oops, forgot it. I'll do it. Thank you @j0k3r

**Pull request merged**
