### PR TITLE
Removed padding on entry view

### PR DESCRIPTION
**Pull request by nicosomb**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| Fixed tickets | #3205
| License       | MIT

See #3205 for screenshots.

### CODE REVIEW

**Comment by tcitworld** [comment]
You also need to do `yarn run build:prod`.

**Comment by nicosomb** [comment]
I don't know why all these files were updated.

**Comment by tcitworld** [comment]
I guess someone forgot to produce them in a PR. See https://github.com/wallabag/wallabag/issues/2651

**Comment by nicosomb** [comment]
OK. Is this PR mergeable?

**Comment by tcitworld** [comment]
yup

**Pull request merged**
