### PR TITLE
add the title of article on the epub export

### PR DESCRIPTION
**Pull request by mart-e**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| License       | MIT

Add the title of the article in an `h1` tag at the beginning of the exported epub.

before vs after result

_Wondering: is it possible to add it on a separated page, to use it as the cover page?_

### CODE REVIEW

**Comment by mart-e** [comment]
Thanks for the review. My idea was to have a cover page when reading the ebook on the my ereader (when sleeping, it shows the first page/cover of the opened book, now it is the table of content).
I will try with a new chapter.

Sorry but I don't have `php-cs-fixer` in my `bin` folder. How can I get it?

**Comment by j0k3r** [comment]
Wow too much changes applied by php-cs-fixer.
Could you just run `php bin/php-cs-fixer fix` without targeting a file?

**Comment by mart-e** [comment]
Actually it crashed (something with PhpCsFixerConfig class not found if I recall) so I assumed I had to target a file.
Do I need to do some config ? I don't know that tool.

**Comment by j0k3r** [comment]
Don't worry I've fixed CS for you 😉

**Comment by j0k3r** [comment]
Thanks @mart-e!

**Comment by j0k3r** [comment]
Failing tests are related to https://github.com/doctrine/DoctrineMigrationsBundle/issues/207

**Pull request merged**
