### PR TITLE
Add tag form submit button always displayed

### PR DESCRIPTION
**Pull request by Simounet**
Submit button always displayed for the add tag form on the entry page. Better UX and accessibility.
Desktop view:
wallabag-desktop

Mobile view:
wallabag-mobile

### CODE REVIEW

**Review by j0k3r — DISMISSED** [review]

**Review by nicosomb — COMMENTED** [review]
Maybe you can target master branch ?

**Review by Kdecherf — COMMENTED** [review]
I'm not necessarily a big fan of keeping an active field like this for tags. However I would see value in putting an edit button next to the tags, instead of the menu item.

**Comment by j0k3r** [comment]
Keep it on 2.6, the 2.6.7 is coming.

**Comment by nicosomb** [comment]
ok for 2.6. 

@Simounet : could you fix assets please?

**Review by j0k3r — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Comment by Kdecherf** [comment]
> I didn't change the behavior. You have to click on the left sidebar to display the form. I've just displayed the button on desktop.

aaaaaaah, got it :+1:

**Pull request merged**
