### PR TITLE
Changed Changelog by using github-changelog-generator from @skywinder

### PR DESCRIPTION
**Pull request by nicosomb**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | yes
| Translation   | no
| Fixed tickets | N/A
| License       | MIT

To replace our old (and manual) CHANGELOG generation, I will use `github-changelog-generator` by @skywinder. 

The command I use for that: `github_changelog_generator --no-compare-link --future-release "2.1.2"` (don't forget to replace the future release).

### CODE REVIEW

**Comment by nicosomb** [comment]
I just saw that we can add a `.github_changelog_generator` file. I will do that in this PR.

**Comment by j0k3r** [comment]
Maybe you should update `RELEASE_PROCESS.md`

**Comment by skywinder** [comment]
🎉

**Comment by nicosomb** [comment]
Thank you @skywinder, I will have a look to these options.

**Pull request merged**
