### PR TITLE
Fix account dropdown width

### PR DESCRIPTION
**Pull request by Simounet**
Before
Desktop
wallabag-desktop-before
Mobile
wallabag-mobile-before

After

Desktop
wallabag-desktop-after
Mobile
wallabag-mobile-after

Have a nice day.

### CODE REVIEW

**Comment by Kdecherf** [comment]
@Simounet which browser did trigger the bug? I am unable to reproduce it on Firefox

**Comment by Simounet** [comment]
Firefox 86 here, maybe a cache issue because I didn't have this issue when I fixed it the first time.

**Comment by Simounet** [comment]
I fixed the thing that was bothering me. It's ready for review now.

**Review by j0k3r — DISMISSED** [review]

**Review by Kdecherf — DISMISSED** [review]
Looks good, @Simounet can you rebase and regenerate the assets please?

**Comment by Simounet** [comment]
Of course. Done.

**Review by Kdecherf — APPROVED** [review]
:+1:

**Review by j0k3r — APPROVED** [review]

**Pull request merged**
