### PR TITLE
Slug for tags

### PR DESCRIPTION
**Pull request by nicosomb**

### CODE REVIEW

**Comment by j0k3r** [comment]
Why do we need this? Are you going to use it somewhere? If yes, why don't you do that in this PR? :)

**Comment by nicosomb** [comment]
I will use it in API (#1432): to fetch entries for a specific tag.

**Comment by j0k3r** [comment]
So maybe you can add the api endpoint right in this PR

**Comment by j0k3r** [comment]
What left to be done here? Do you need help?

**Comment by j0k3r** [comment]
Updated & rebased.

**Comment by j0k3r** [comment]
@nicosomb I think we can merge that and check later for the missing endpoint.

**Comment by nicosomb** [comment]
:+1:

**Pull request merged**
