### PR TITLE
Update all deps

### PR DESCRIPTION
**Pull request by j0k3r**
- lock `shipmonk/composer-dependency-analyser` because I don't know how to workaround the error
- update parameter PHPDoc for `UserMailer` following `TwigSwiftMailer` update
- migrate PHPUnit config using `--migrate-configuration`

### CODE REVIEW

**Review by yguedidi — APPROVED** [review]

**Comment by yguedidi** [comment]
@j0k3r maybe rebase on latest master because of other deps upgrades

**Comment by j0k3r** [comment]
> @j0k3r maybe rebase on latest master because of other deps upgrades

It's only JS deps that got merged, but anyway I've rebased

**Comment by janedbal** [comment]
Hi, maintainer of [shipmonk/composer-dependency-analyser](https://github.com/shipmonk-rnd/composer-dependency-analyser) here.

> lock shipmonk/composer-dependency-analyser because I don't know how to workaround the error

Looks like you had trouble updating the tool from 1.5 to 1.6. Seeing [the errors](https://github.com/shipmonk-rnd/composer-dependency-analyser/actions/runs/9940303788/job/27456706140?pr=163#step:9:24), it only found usages of your bundles in `app/AppKernel.php`, those were previously not seen by the tool.

So I believe you only need to remove few ignores from [your config](https://github.com/wallabag/wallabag/blob/master/composer-dependency-analyser.php#L17) and decide if those found dev bundles shouldnt be moved to `require`.

**Comment by j0k3r** [comment]
@janedbal Hi, thanks for the hint. I didn't set up the analyzer myself so I didn't took the time to investigate much more.

**Comment by j0k3r** [comment]
@janedbal fixed, thanks https://github.com/wallabag/wallabag/pull/7622

**Pull request merged**
