### PR TITLE
Added new tag form in mobile view for Material theme

### LINKED ISSUE #2376: Unable to add tags in the mobile web version
### Issue details

When viewing an entry in the mobile web version, adding a tag is hidden from the sidebar. Tags seem to be intentionally hidden in CSS on small screens. It makes the mobile app much less useful.
### Environment
- wallabag 2.1.1
- OS: Safari on iOS 10, iPhone 6
- Theme: Material
### Steps to reproduce/test case

Open any entry in a mobile browser. You can also use Chrome and switch to mobile view with Safari as user agent.

### PR DESCRIPTION
**Pull request by nicosomb**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | yes
| Fixed tickets | #2376 
| License       | MIT

Fix #2376

### CODE REVIEW

**Comment by j0k3r** [comment]
Screenshot?

**Comment by j0k3r** [comment]
You can remove the last commit.

**Comment by nicosomb** [comment]
@j0k3r done

**Pull request merged**
