### PR TITLE
Italian translation for configuring_mobile.rst

### PR DESCRIPTION
**Pull request by matteocoder**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | no
| Documentation | yes
| Translation   | yes
| Fixed tickets | #...
| License       | MIT

### CODE REVIEW

**Comment by j0k3r** [comment]
Your file should be here `docs/ita/user/configuring_mobile.rst` instead.

**Comment by matteocoder** [comment]
I'm sorry if I put it in the wrong place. Should I create a new pull request to correct it?

**Comment by j0k3r** [comment]
Yeah could you start over?

**Comment by nicosomb** [comment]
And as @j0k3r is an other PR, can you rename the `ita` folder into `it` please?

**Pull request closed without merging**
