### PR TITLE
Updated text iTunes to App Store.

### LINKED ISSUE #6950: Change "iTunes" to "App Store"
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Change any iOS app links' descriptions to be "App Store" rather than "iTunes" 

**Describe alternatives you've considered**
N/A

**Additional context**
Apple transitioned away from iTunes to the App store a while ago, so the updated name should be used here.

### PR DESCRIPTION
**Pull request by sonvir249**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | yes
| CHANGELOG.md  | no
| License       | MIT

Fixes #6950

### CODE REVIEW

**Review by j0k3r — DISMISSED** [review]
Thanks!

**Comment by sonvir249** [comment]
> Thanks!

@j0k3r why there are no hacktoberfest labels?

**Comment by j0k3r** [comment]
> @j0k3r why there are no hacktoberfest labels?

Because the repo thas the `hacktoberfest` topic and it's enough to validate your participation

**Review by j0k3r — APPROVED** [review]

**Comment by sonvir249** [comment]
> > @j0k3r why there are no hacktoberfest labels?
> 
> Because the repo thas the `hacktoberfest` topic and it's enough to validate your participation

got it, Thanks.

**Pull request merged**
