### PR TITLE
Dark Material theme

### LINKED ISSUE #1521: Dark material theme

### PR DESCRIPTION
**Pull request by BoyMechanicus**
| Q             | A
| ------------- | ---
| New feature?  | yes
| Documentation | yes
| License       | MIT

### CODE REVIEW

**Comment by Kdecherf** [comment]
Hello @BoyMechanicus,

Thanks for your work :)

I think it could be interesting to merge the dark variant inside the Material theme and to use a toggle to change between the light and dark variants. For this to work, I think we should separate the color directives from current scss files and having one additional scss file for each variant. This way, the maintenance would be easier than having two separate Material themes.

Thoughts, @wallabag/core?

**Comment by j0k3r** [comment]
@Kdecherf I agree! We can also improve it for MacOS Mojave :star2: https://paulmillr.com/posts/using-dark-mode-in-css/

**Comment by BoyMechanicus** [comment]
It will need more than a css tweak, because some of the images needed to be inverted to be seen on dark backgrounds.

**Comment by Kdecherf** [comment]
Well, images can be inverted using css, see https://github.com/wallabag/wallabag/pull/3786

**Comment by vdbm** [comment]
I was sent here by Jeremy (@j0k3r) from #3973, but I have no clear idea on how to best support you, as it is not clear what you want to achieve with version 2.4 (I am not a developer, not a geek and not greatly familiar with github). 
What I do know is what I wrote on #3973: the macOS experience is quite poor at the moment. The only way to view saved articles on wallabag.it is within the browser, but the site is complicated:
- It is not clear what Subscription, Config and API Clients Management actually mean for the normal non-geek user, and how they should be used. 
- The difference between the four types of articles (read/unread, starred/unstarred, archived/unarchived, tagged/untagged) is not clear.
- The site has no visual customization settings available (besides the ugly Baggy theme). If you want dark mode or font choices, you would need to install a non-wallabag extension (e.g. Reader View) as a workaround. You will have to develop a dark grey and black mode, a way to vary the margin, the font type and size, or the line height. 
- You will also need more sharing options and make the whole thing more customizable.
In general, you need to provide more guidance to the user, rather than assume that they are able to figure things out by themselves.

**Comment by j0k3r** [comment]
As there is no progress on that PR since quite some time I removed the milestone.

**Comment by nicosomb** [comment]
@BoyMechanicus any news on your branch? You need to make some changes (mainly on rss feeds and two factor authentication)

**Comment by BoyMechanicus** [comment]
I do indeed have to sit down and twaddle with the sauce as they say. Give me a few days and I'll sneak something in.

**Comment by BoyMechanicus** [comment]
Made an update. It was 99% a css file change this time.

**Comment by BoyMechanicus** [comment]
I am interested in implementing the features mentions in Mojave, but I do not have a mac to test that on. Is there a reliable tool to check for that?

**Comment by BoyMechanicus** [comment]
Incorporated some changes from https://github.com/wallabag/wallabag/commit/652cb58d59c9cb3d1f448914e0568e87eba90b16 a couple fixes I missed

**Comment by mere-teresa** [comment]
Someone is available to review it? I would like to have this dark theme so bad.
@tcitworld maybe?

**Comment by j0k3r** [comment]
I'm closing this PR in favor of https://github.com/wallabag/wallabag/pull/4725.
Check my comment for the reason https://github.com/wallabag/wallabag/pull/4725#issuecomment-725672799

Also, people can still use that new theme of course.

**Pull request closed without merging**
