### PR TITLE
Miscellaneous additions

### PR DESCRIPTION
**Pull request by moparisthebest**
This adds 3 bits of functionality, one per commit.  Rebased on the dev branch this time as per the contributing guidelines. :)

### CODE REVIEW

**Comment by tcitworld** [comment]
Wow. That's great work. :)

The tagging feature will be very appreciated by browser and mobile apps.

**Comment by tcitworld** [comment]
Will test and merge tonight.

**Comment by moparisthebest** [comment]
If you want to test the adding tag on article creation you can use the wallabag shell script from here:

https://github.com/moparisthebest/wallabag_scripts

I wrote all of this stuff to make it easier to import/tag/mark read all of my bookmarks and mass delete all the ones where content could not be fetched. :) (wallabag is awesome!)

**Comment by nicosomb** [comment]
Just a post to thank you :-)

**Pull request merged**
