### PR TITLE
Integrate graby

### LINKED ISSUE #1262: Implement graby into wallabag v2
I think @j0k3r knows what he has to do with https://github.com/j0k3r/graby. Good luck! 

graby will replace Full-Text RSS for parsing articles.

### PR DESCRIPTION
**Pull request by j0k3r**
This should fix #1262.
It stills needs to fix how graby will read site_config directory, this is why tests are failing atm.

I also implement #972. It just save the Open Graph image in the database. I didn't display it.

 - [x] Fix graby-site-config
 - [x] Store image preview
 - [x] Grab open graph information when content failed to be fetched (like title, summary, etc ...)

### CODE REVIEW

**Comment by j0k3r** [comment]
Graby returns the _final_ url, like if someone bag a `http://t.co` it will return the url the final url. Should we override this irk in wallabag or keep the original submitted url?

**Comment by nicosomb** [comment]
Oh, nice! We have to avoid URL like t.co I think, so wallabag should store the final URL.

**Comment by j0k3r** [comment]
Job done.
I've introduced a class called `ContentProxy` (_yeah it's not the best class name, feel free to share a good one if you have_) that take care of getting the content from an url and update the entry (using graby). So the way we grab content is in one place (instead of in the Core and in the Api).

graby will surely evolve in the future (1.0.0 isn't ready yet) but it'll be as a dependency, so it's not a problem.

**Comment by nicosomb** [comment]
Nice job. The title still contains "WIP", is that still true?

**Comment by j0k3r** [comment]
Nope :-)

**Pull request merged**
