### PR TITLE
fix #972: add preview pictures

### LINKED ISSUE #972: Preview picture for each article
As @moafred (from Bookeen team) told me yesterday, we can use og:image meta to get a preview picture for each article. 
This tag is used by twitter and facebook to generate preview in posts. 

For example, with this article http://www.lemonde.fr/pixels/article/2014/12/18/affaire-sony-pictures-la-strategie-anti-piratage-d-hollywood-revelee_4542100_4408996.html, we have this meta :

```
<meta property="og:image" content="http://s1.lemde.fr/image/2014/12/17/600x315/4542146_3_8afb_le-legendaire-signe-surplombant-hollywood-en_443f1e6556ca1af14830f9d266203bcf.jpg" />
```

It can be useful for generating nice ePUB files (instead of wallabag logo). 

@tcitworld Are you interested to have a look to this feature?

### PR DESCRIPTION
**Pull request by nicosomb**

### CODE REVIEW

**Comment by modos189** [comment]
Wow! Good)

**Comment by modos189** [comment]
I thing, better to use Card Reveal
http://materializecss.com/cards.html#reveal

**Comment by j0k3r** [comment]
What about baggy?

**Comment by nicosomb** [comment]
@j0k3r grrr forgot it!
@modos189 oh nice! thak you!

**Comment by nicosomb** [comment]
@modos189 maybe can you do it please? you'll do it better than me.

**Comment by tcitworld** [comment]
Pictures should stick to the bottom of the card, right ?

**Comment by nicosomb** [comment]
what do you mean? No text (like action buttons) under the picture?

**Comment by tcitworld** [comment]
Yup. If there's any text to show, show it above. 
Just my opinion.

**Comment by tcitworld** [comment]
(Referring to the third card)

**Comment by nicosomb** [comment]
@modos189 it's a work for you!

**Comment by modos189** [comment]
Ok

**Comment by nicosomb** [comment]
Picture preview added on baggy theme.

**Comment by nicosomb** [comment]
Maybe we can merge this 1st version of preview picture. Then @modos189 will enhance it.

**Comment by j0k3r** [comment]
Agreed.

**Pull request merged**
