### PR TITLE
V2 Edit title

### LINKED ISSUE #218: Edit title
Avoir la possibilité de changer le titre d'un élément sauvegardé pour lui donner un titre personnalisé (avec, par exemple, une petite icône d'un crayon à droite de celui-ci). 
Utile s'il n'est d'origine pas très précis. 

Voici un soucis, par exemple, avec certaines pages: 
cinesion-films

### PR DESCRIPTION
**Pull request by j0k3r**
Fix #218

I mean basic, because there is no javascript at all. It could be a nice edit-in-place. But for the moment, it is simple.

### CODE REVIEW

**Comment by nicosomb** [comment]
it works. Why is there a `is public` checkbox?

**Comment by j0k3r** [comment]
Because it's not only related to edit the title, but the saved article.
Like for tags, I can comment this feature for the moment.

**Comment by nicosomb** [comment]
I think you can: I click on "edit title", I don't want to change entry's status.

**Comment by nicosomb** [comment]
OK, I merge.

**Pull request merged**
