### PR TITLE
Fix redirection after action in search results

### PR DESCRIPTION
**Pull request by nicosomb**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  |no
| BC breaks?    |no
| Deprecations? |no
| Tests pass?   | yes
| Documentation |no
| Translation   | yes
| CHANGELOG.md  |no
| License       | MIT

Fix https://github.com/wallabag/wallabag/issues/7821

### CODE REVIEW

**Review by j0k3r — DISMISSED** [review]

**Comment by nicosomb** [comment]
@j0k3r no test was written for this feature (the redirection after an action in search results). Do we need to write one? I prefer ask you because you accepted the PR 😉

**Comment by j0k3r** [comment]
Oh I was sure we do have test for that. So yes, you can write tests then :)

**Comment by yguedidi** [comment]
shouldn't this target 2.6, being a bugfix to a bug in 2.6.8+?

**Comment by nicosomb** [comment]
@yguedidi I don't know ... because I don't know if we plan to release a new patch release on 2.6.x unless a critical bug.

**Comment by yguedidi** [comment]
@nicosomb to me, unless we officially communicate that 2.6.x in not maintained anymore (and I think this can happen only at least after the 2.7.0 release), we should deliver on bugfixes in that branch

**Comment by nicosomb** [comment]
New PR #7827

**Pull request closed without merging**
