### PR TITLE
Fix reading speed not defined when user was created via config page

### LINKED ISSUE #2004: Reading speed not defined when creating user via config page
### Issue details

If I create a user via config page (tag "Add a new user"), this new user don't have reading speed in his configuration. When he'll add new articles, he will have an error when he'll display entries list.

### PR DESCRIPTION
**Pull request by nicosomb**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| Fixed tickets | #2004 
| License       | MIT

Fix #2004

About tests, I need your opinion.

### CODE REVIEW

**Comment by j0k3r** [comment]
Is there a test for creating a user from the config page? If yes, we should check that the config is created with all the required fields.

**Comment by nicosomb** [comment]
It's not a field ...

**Comment by j0k3r** [comment]
It is https://github.com/wallabag/wallabag/blob/master/src/Wallabag/CoreBundle/Entity/Config.php#L81

**Comment by nicosomb** [comment]
Yes it's a property, you're right. But it's not a field in the config page when we create a new user.
So what can I test?

**Comment by j0k3r** [comment]
- retrieve the config object associated to the created user
- assert all _properties_ are defined and not empty

**Pull request merged**
