### PR TITLE
fix #1283: display the good title for each category

### LINKED ISSUE #1283: Display current category name
As @NumEricR said in #1282: 

> I think it should be better to display current category as title in main area: Unread, Favorites, ...

### PR DESCRIPTION
**Pull request by nicosomb**

### CODE REVIEW

**Comment by modos189** [comment]
Good. This can be used to highlight menu

**Comment by nicosomb** [comment]
Thanks for merging, but when I assign a PR to someone (this one to @j0k3r for example), I want to have the opinion of @j0k3r ;-)

**Comment by nicosomb** [comment]
even if it's a simple PR like there.

**Comment by j0k3r** [comment]
@nicosomb this one seems ok :)

**Pull request merged**
