### PR TITLE
Translation for Persian

### PR DESCRIPTION
**Pull request by mabkenar**
Translation file for the 'Persian' language. Also recognized by fa_IR. Also known (in the Persian language) as Farsi. Also written like فارسی in Persian. All said, please call the language just 'Persian'.

### CODE REVIEW

**Comment by nicosomb** [comment]
Thank you @mabkenar!
* Can you update your PR here: https://github.com/wallabag/wallabag/blob/v2/app/config/config.yml#L33
* Can I add you to a new wallabag organization, "translators"?

**Comment by mabkenar** [comment]
You're welcome. Thank you for making the awesome thing that I use everyday!

- Sure, I have edited config.yml file.
- And yes, I am more than happy if you do.

**Comment by nicosomb** [comment]
Thank you!

**Comment by mabkenar** [comment]
Where can I test the new translation? Is there a demo version that is directly synced with this branch?
I want to see how does it look like to have a Right-To-Left translated interface in an LTR page layout. 

As a next step, we can think of setting the page style with "direction: rtl" if any RTL language is set.

**Comment by nicosomb** [comment]
> Is there a demo version that is directly synced with this branch?

Not yet, but it's planned (in my head :-) )

You're totally right for the setting: we already have this issue #1285, fell free to update it if it's necessary.

**Comment by nicosomb** [comment]
capture du 2016-02-17 06 40 27

**Comment by mabkenar** [comment]
Although it is still LTR, it doesn't look bad! 
If you point me to a file where I can translate the rest of English words that I see in this screenshot, I will be happy to translate. I mean, 'import', 'internal settings', 'tagging rules', and others, if any.

**Comment by tcitworld** [comment]
They are some strings here : https://github.com/wallabag/wallabag/tree/v2/app/Resources/CraueConfigBundle/translations and here : https://github.com/wallabag/wallabag/blob/v2/src/Wallabag/CoreBundle/Resources/translations/validators.fr.yml

**Comment by nicosomb** [comment]
I will publish a documentation about "how to translate wallabag v2" in few minutes.

**Comment by 0wnrepo** [comment]
:+1:

**Comment by nicosomb** [comment]
see #1679

**Comment by mabkenar** [comment]
Thank you very much @nicosomb for your great work!

**Comment by nicosomb** [comment]
http://wallabag.readthedocs.org/en/v2/developer/translate.html

**Comment by mabkenar** [comment]
selection_128
The estimated time for reading is displayed wrong. It will be better if the word 'min' is also translated (I just tested that in my browser). In the current situation, the mix between LTR and RTL words has made the order of the words completely messed up.
Is the word 'min' in the screenshot anywhere to be translated?

**Comment by nicosomb** [comment]
Please open a new issue ;-)

**Comment by mabkenar** [comment]
Yes, sir :)

**Pull request merged**
