### PR TITLE
Enable Swagger JSON output in routing.yml

### LINKED ISSUE #7462: API/documentation: Add OpenAPI JSON endpoint
**Is your feature request related to a problem? Please describe.**
If there's an OpenAPI 3 JSON specification available, I can automatically generate part of a Wallabag client (or even an API compatible server!)

It's supported by the Nelmio library you're using, but not turned on.

**Describe the solution you'd like**
It looks like https://symfony.com/bundles/NelmioApiDocBundle/current/index.html#installation says that you need something as "simple" as 

```
app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
```
next to https://github.com/wallabag/wallabag/blob/master/app/config/routing.yml#L5 but I don't know how to do it with the syntax you're using.

**Describe alternatives you've considered**
Learning enough about Symphony and hacking routing.yaml myself

### PR DESCRIPTION
**Pull request by voltagex**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes/no
| BC breaks?    |  no
| Deprecations? | no
| Tests pass?   | yes?
| Documentation | yes
| Translation   | no
| CHANGELOG.md  | no
| License       | MIT

Fixes #7462

Apologies @j0k3r I had accidentally commented this part of the template out

### CODE REVIEW

**Comment by j0k3r** [comment]
Why?

**Comment by voltagex** [comment]
As I said in the issue I raised, this allows client code to be automatically generated.

**Comment by j0k3r** [comment]
Ok right. But which issue?

**Comment by voltagex** [comment]
Sorry! I had managed to break the template and didn't see it when you replied.

https://github.com/wallabag/wallabag/issues/7462 I have also updated the PR description

**Review by j0k3r — APPROVED** [review]
Thanks, looks ok.

**Review by yguedidi — APPROVED** [review]

**Pull request merged**
