### PR TITLE
Use graby 1.2

### PR DESCRIPTION
**Pull request by tcitworld**
To add timeout to the requests.

May help #1661

### CODE REVIEW

**Comment by 0wnrepo** [comment]
Testing..

**Comment by tcitworld** [comment]
It was just to force you to be at the latest version of graby. Can you `composer update` and tell me the Graby version you're using ? Search for graby in your `composer.lock` file, the number version is just beneath it.

**Comment by j0k3r** [comment]
`~1.0` will install graby 1.2.0.

**Comment by tcitworld** [comment]
Yeah, that's why I closed. :tired_face:

**Comment by j0k3r** [comment]
Can we continue discussion on the main thread instead #1661? :)

**Pull request closed without merging**
