### PR TITLE
Refactor aka wallabag v2

### PR DESCRIPTION
**Pull request by tcitworld**
This is a work in progress branch about the upcoming v2 of wallabag using Symfony 2.
The branch is really active and really unstable, things can be broken, can change without any notification.
Since we are rebuilding it, any suggestion are welcome :grin:

Feel free to test it but don't use it in production right now.
You can follow these few steps to test it:

```
git clone https://github.com/wallabag/wallabag.git -b refactor
cd wallabag
composer install
php app/console wallabag:install
php app/console server:run
```

If you see something wrong or bad, you can open a new issue with the "v2" in the title or you can come and talk to us on [gitter](https://gitter.im/wallabag/wallabag).

### CODE REVIEW

**Comment by tcitworld** [comment]
Et bien. Wow wow wow.

**Comment by nicosomb** [comment]
I just saw your wow comments ;-)

**Comment by tcitworld** [comment]
;)

**Comment by marienfressinaud** [comment]
> Sorry, we could not display the entire diff because too many files (2,134) changed.

Ah ah! :D

**Comment by nicosomb** [comment]
:-D Tu verras quand tu coderas FreshRSS v2 ;-)

**Comment by foxmask** [comment]
before you improve the API, urls looks like this : 

* /api/u/{user}/entries.json'
* /api/u/{user}/entry/{entry}

But right now we dont have the user anymore, does this mean that the API will take a token that makes the user parm unuseful ?

**Comment by nicosomb** [comment]
Yes, we'll have a token.

**Comment by nicosomb** [comment]
I close this PR to rename the branch.

**Pull request closed without merging**
