### PR TITLE
fix type hint for User

### PR DESCRIPTION
**Pull request by nicosomb**

### CODE REVIEW

**Comment by j0k3r** [comment]
Well, if there is this error, this means there is no test that cover that line :warning:

**Comment by nicosomb** [comment]
OK, but we never wrote tests for methods like that. What do you suggest?

**Comment by j0k3r** [comment]
How did you see the error?

**Comment by nicosomb** [comment]
Not locally, when I deployed and when I ... launch a command maybe, I can't remember, it was yesterday.

**Pull request merged**
