### PR TITLE
fix security bug with PHP_AUTH_USER

### PR DESCRIPTION
**Pull request by tcitworld**
Thanks to M. Holzäpfel.

### CODE REVIEW

**Comment by nicosomb** [comment]
I just sent an email to Milan Holzäpfel, I asked him to make a review of your PR (and I forgot you in cc ..).

**Comment by tcitworld** [comment]
Well, the PR is just his patch. I didn't got the time to test it in all kinds of configurations though, so I open it to everyone.

**Comment by tcitworld** [comment]
It fixes the bug, that's for sure. We just need to be sure if it works on particular installations.

**Comment by j0k3r** [comment]
But what's the bug? Any description somewhere?

**Comment by j0k3r** [comment]
Well, I'm ok with that :+1:

**Comment by tcitworld** [comment]
I'm sending you the details by email.

**Comment by j0k3r** [comment]
@tcitworld Nico already send them to me, thanks :)

**Comment by tcitworld** [comment]
Okay, then I will merge before next version (which I would like to be out tomorrow, I'm away starting from Friday)

**Comment by nicosomb** [comment]
Do you want / can you write a blog post about 1.9.2?

**Comment by tcitworld** [comment]
Yup, I will write it tomorrow.

**Pull request merged**
