### PR TITLE
Wrong installation instructions in README

### PR DESCRIPTION
**Pull request by mart-e**
| Q             | A
| ------------- | ---
| Documentation | yes
| License       | MIT

 * composer is creating a subdirectory
 * console file is in app folder, not bin

**Sidenote**
After installing linked [composer installation doc](https://getcomposer.org/download/), I got a local `composer.phar` file, not a `composer` command (but I am not familiar with the program)

### CODE REVIEW

**Comment by j0k3r** [comment]
> composer is creating a subdirectory

Yes, it creates a `vendor` dir where all dependencies are stored.

> console file is in app folder, not bin

It looks strange to me because with the latest alpha this file should be in the bin folder.
Could you please check that:
- you have this line in the `composer.json`

 ````
 "symfony/symfony": "3.0.*",
 ```
- the version number just below this line in the `composer.lock`

 ```
 "name": "symfony/symfony",
 ```
 It should be `"version": "v3.0.1",`.

**Comment by mart-e** [comment]
> you have this line in the composer.json
> `"symfony/symfony": "3.0.*",`

No I don't, I get `~2.7.0`.

So is it possible the error is in the command `SYMFONY_ENV=prod composer create-project wallabag/wallabag wallabag "2.0.*@alpha" --no-dev`? Should we specify the alpha number somewhere?

**Comment by j0k3r** [comment]
Ok, do you still have the log of the `composer create-project` ? If yes, could you paste it here?

**Comment by mart-e** [comment]
```
# set -x SYMFONY_ENV prod
# ./composer.phar create-project wallabag/wallabag wallabag "2.0.*@alpha" --no-dev
Installing wallabag/wallabag (2.0.0-alpha.0)
  - Installing wallabag/wallabag (2.0.0-alpha.0)
    Loading from cache

Created project in wallabag
Loading composer repositories with package information
Installing dependencies from lock file
  - Installing doctrine/collections (v1.3.0)
    Loading from cache

  - Installing twig/twig (v1.21.2)
    Loading from cache

  - Installing psr/log (1.0.0)
    Loading from cache

  - Installing doctrine/lexer (v1.0.1)
    Loading from cache
  - Installing doctrine/inflector (v1.0.1)
    Loading from cache

  - Installing doctrine/cache (v1.4.2)
    Loading from cache

  - Installing doctrine/annotations (v1.2.7)
    Loading from cache

  - Installing doctrine/common (v2.5.1)
    Loading from cache

  - Installing symfony/symfony (v2.7.4)
    Loading from cache

  - Installing jdorn/sql-formatter (v1.2.17)
    Loading from cache

  - Installing doctrine/doctrine-cache-bundle (v1.0.1)
    Loading from cache

  - Installing doctrine/dbal (v2.5.1)
    Loading from cache

  - Installing doctrine/doctrine-bundle (v1.5.1)
    Loading from cache

  - Installing doctrine/instantiator (1.0.5)
    Loading from cache

  - Installing ezyang/htmlpurifier (v4.7.0)
    Loading from cache

  - Installing willdurand/negotiation (1.4.0)
    Loading from cache

  - Installing willdurand/jsonp-callback-validator (v1.1.0)
    Loading from cache

  - Installing friendsofsymfony/rest-bundle (1.7.1)
    Loading from cache

  - Installing friendsofsymfony/user-bundle (dev-master 6b7bb04)
    Cloning 6b7bb04c6d507bb5356bf70b2d1bc30ce64ffc60

  - Installing react/promise (v2.2.1)
   Loading from cache

  - Installing guzzlehttp/streams (3.0.0)
    Loading from cache

  - Installing guzzlehttp/ringphp (1.1.0)
    Loading from cache

  - Installing incenteev/composer-parameter-handler (v2.1.1)
    Loading from cache

  - Installing simplepie/simplepie (1.3.1)
    Loading from cache

  - Installing neitanod/forceutf8 (v1.4)
    Loading from cache

  - Installing monolog/monolog (1.17.1)
    Loading from cache

  - Installing j0k3r/php-readability (v1.0.4)
    Loading from cache

  - Installing j0k3r/graby-site-config (1.0.2)
    Loading from cache

  - Installing htmlawed/htmlawed (1.1.19)
    Loading from cache

  - Installing guzzlehttp/guzzle (5.3.0)
    Loading from cache

  - Installing fin1te/safecurl (v1.1)
    Loading from cache

  - Installing j0k3r/graby (1.0.0-alpha.1)
    Loading from cache

  - Installing phpoption/phpoption (1.5.0)
    Loading from cache

  - Installing phpcollection/phpcollection (0.4.0)
    Loading from cache

  - Installing jms/parser-lib (1.0.0)
    Loading from cache

  - Installing jms/metadata (1.5.1)
    Loading from cache

  - Installing jms/serializer (0.16.0)
    Loading from cache
  - Installing doctrine/orm (v2.5.1)
    Loading from cache

  - Installing lexik/form-filter-bundle (v4.0.0)
    Loading from cache

  - Installing liip/theme-bundle (1.1.3)
    Loading from cache

  - Installing mgargano/simplehtmldom (1.5)
    Loading from cache

  - Installing michelf/php-markdown (1.5.0)
    Loading from cache

  - Installing nelmio/api-doc-bundle (2.9.0)
    Loading from cache

  - Installing nelmio/cors-bundle (1.4.0)
    Loading from cache

  - Installing pagerfanta/pagerfanta (v1.0.3)
    Loading from cache

  - Installing sensiolabs/security-checker (v3.0.1)
    Loading from cache

  - Installing sensio/distribution-bundle (v3.0.31)
    Loading from cache

  - Installing sensio/framework-extra-bundle (v3.0.10)
    Loading from cache

  - Installing kriswallsmith/assetic (v1.3.0)
    Loading from cache

  - Installing symfony/assetic-bundle (v2.7.0)
    Loading from cache

  - Installing symfony/monolog-bundle (v2.7.1)
    Loading from cache

  - Installing symfony/assetic-bundle (v2.7.0)
    Loading from cache

  - Installing symfony/monolog-bundle (v2.7.1)
    Loading from cache

  - Installing swiftmailer/swiftmailer (v5.4.1)
    Loading from cache

  - Installing symfony/swiftmailer-bundle (v2.3.8)
    Loading from cache

  - Installing tecnick.com/tcpdf (6.2.11)
    Loading from cache

  - Installing twig/extensions (v1.3.0)
    Loading from cache

  - Installing willdurand/hateoas (v2.6.0)
    Loading from cache

  - Installing jms/serializer-bundle (0.13.0)
    Loading from cache

  - Installing willdurand/hateoas-bundle (0.5.0)
    Loading from cache

```
So indeed I am getting alpha 0 instead of 2

**Comment by j0k3r** [comment]
Looks weird.
I just tested and I got

```
j0k@me:/tmp$ composer create-project wallabag/wallabag wallabag "2.0.*@alpha" --no-dev
Installing wallabag/wallabag (2.0.0-alpha.2)
  - Installing wallabag/wallabag (2.0.0-alpha.2)
```

Maybe we should force the tag in the readme file instead.
Could you update your PR accordingly ?

**Comment by mart-e** [comment]
Ok now we are getting somewhere. 
```
# ./composer.phar create-project wallabag/wallabag wallabag-dev "2.0.0-alpha.0" --no-dev
Installing wallabag/wallabag (2.0.0-alpha.0)
  - Installing wallabag/wallabag (2.0.0-alpha.0)
# ./composer.phar create-project wallabag/wallabag wallabag-dev "2.0.0-alpha.2" --no-dev
                                                                        
  [InvalidArgumentException]                                            
  Could not find package wallabag/wallabag with version 2.0.0-alpha.2.  
                                                                        
...
Do I need to do something else after installing composer? I just installed it yesterday following the linked guide.

**Comment by j0k3r** [comment]
Wow, so it seems that your composer doesn't get fresh packages.

Could you try:

```
./composer.phar clearcache
./composer.phar selfupdate
```

and then retry.

**Comment by mart-e** [comment]
It did cleaned the cache but I still got the old alpha.0. 
So it looks like the issue is on my machine (I have an old debian wheezy, could be related?) and not on wallabag so I am closing this PR.
Will investigate and come back with some news

**Comment by j0k3r** [comment]
All right, please come back to us when you've done with your investigation.

**Comment by mart-e** [comment]
Ok I think I got it! d4aa17436700713fcb4eb5c4a2c48182f37c3b5e dropped the support for php 5.4 which is the latest version on [debian wheezy](https://packages.debian.org/wheezy/php5).
Time to upgrade I guess :-/

**Comment by j0k3r** [comment]
Oh right. This is it.
Sorry about that and good luck with your install update.

**Pull request closed without merging**
