### PR TITLE
Hide export button if we are not on entries list

### PR DESCRIPTION
**Pull request by nicosomb**

### CODE REVIEW

**Comment by tcitworld** [comment]
Isn't something missing here ?

**Comment by nicosomb** [comment]
No, why?

**Comment by tcitworld** [comment]
I didn't have or go or take a deep look, but won't this hide it every time ?

**Comment by nicosomb** [comment]
We have this in init.js (`init_export()`): 

```
    if ($("div").is("#export")) {
        $('#button_export').show();
        $('.button-collapse-right').sideNav({ edge: 'right' });
    }
```

**Comment by tcitworld** [comment]
Right. Your change should have been there from start. :-)

**Pull request merged**
