### PR TITLE
Removed Carrot & Scuttle share

### PR DESCRIPTION
**Pull request by nicosomb**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | yes, kind of 
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | yes
| CHANGELOG.md  | no
| License       | MIT

Carrot and Scuttle services are no longer available. No need to deprecate these services.

Less code, less bug.

### CODE REVIEW

**Review by j0k3r — CHANGES_REQUESTED** [review]
Could you update our PR against the master and regenerate assets `yarn build:prod` ?

**Comment by nicosomb** [comment]
Oh, you want to release this in the next patch?

**Comment by j0k3r** [comment]
😆 
Sorry, I'm a kind of bot ... I write master instead of 2.6.0 ...

**Comment by nicosomb** [comment]
😁
My PR seems up to date with 2.6.0 ...

**Comment by j0k3r** [comment]
Just rebuild assets then

**Comment by nicosomb** [comment]
I hope it will be ok.

**Comment by nicosomb** [comment]
> I hope it will be ok.

Yes it is 🎉

**Review by j0k3r — APPROVED** [review]

**Pull request merged**
