### PR TITLE
change timeout because scrutinizer failed

### PR DESCRIPTION
**Pull request by nicosomb**
see https://scrutinizer-ci.com/g/wallabag/wallabag/inspections/1ba56fc0-e1d6-4d6a-863d-9b18927b011d/log

### CODE REVIEW

**Comment by j0k3r** [comment]
Does it fails like that on every PR ?

**Comment by nicosomb** [comment]
yes https://scrutinizer-ci.com/g/wallabag/wallabag/inspections

**Comment by j0k3r** [comment]
It's really really strange that Scrutinizr wait half an hour to get the coverage when the travis build took only few minutes.

Well ok, I found the problem.
We do not generate coverage anymore since it tooks age to generate ... https://github.com/wallabag/wallabag/commit/9a014e48d65f30d0ca03bcc1eff5243421af52ca

I think it's better to disable `external_code_coverage` for now.

**Comment by nicosomb** [comment]
done

**Comment by nicosomb** [comment]
Back on Scrutinizer https://scrutinizer-ci.com/g/wallabag/wallabag/inspections/b3c52478-4cc2-4dc6-a38d-6e857030dd8b

**Pull request merged**
