### PR TITLE
Starred and Archived clears if article is already exists

### PR DESCRIPTION
**Pull request by Rurik19**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | no
| Documentation | no
| Translation   | no
| Fixed tickets | issue #2089
| License       | MIT

### CODE REVIEW

**Comment by j0k3r** [comment]
Thanks for that !
Could you add a test to cover that change, sth [like this one](https://github.com/wallabag/wallabag/blob/master/src/Wallabag/ApiBundle/Tests/Controller/WallabagRestControllerTest.php#L259) where you didn't send starred & archive value and just be sure that the initialy value aren't changed?

**Comment by Rurik19** [comment]
Sure, look next commit

**Comment by Rurik19** [comment]
Sorry last commit is wrong

**Comment by Rurik19** [comment]
Now it is OK

**Comment by j0k3r** [comment]
Could you run `php bin/php-cs-fixer fix src/` to fix CS?

**Comment by Rurik19** [comment]
bin/php-cs-fixer is a link to  ../vendor/fabpot/php-cs-fixer/php-cs-fixer 
but there no such directory as /vendor/fabpot

**Comment by j0k3r** [comment]
Ok no problem, I'l do that on my own.
Thanks for the fix by the way 👍

**Pull request merged**
