### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by jrottenberg**
Trying to get #220 resurrected ;-)

I've tried to follow the instructions from the Vagrantfile + as few tweaks as possible to get the application up and running.

It should be trivial form there to start populating official images of the application on the registry.

Also it is as small as possible (granted I've added all the nice to have php modules) :
```
REPOSITORY                  TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
wallabag                    latest              d0ec9aecc4b1        4 minutes ago       305.5 MB
```

Here is the build log
```
$ docker build  -t wallabag . && docker run -it -p 8080:80 wallabag
Sending build context to Docker daemon 36.93 MB
Sending build context to Docker daemon
Step 0 : FROM ubuntu:trusty
 ---> 2d24f826cb16
Step 1 : RUN apt-get -qq update &&         DEBIAN_FRONTEND=noninteractive apt-get install -y curl apache2 php5 php5-xdebug php5-sqlite php5-pgsql php5-mysql php5-gd php5-curl php5-tidy&&         apt-get clean -y &&         echo "ServerName localhost" >> /etc/apache2/apache2.conf &&         rm -rf /var/www/html
 ---> Running in 4117baf48a8f
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  apache2-bin apache2-data ca-certificates fontconfig-config fonts-dejavu-core
  krb5-locales libapache2-mod-php5 libapr1 libaprutil1 libaprutil1-dbd-sqlite3
  libaprutil1-ldap libasn1-8-heimdal libcurl3 libedit2 libfontconfig1
  libfreetype6 libgd3 libgssapi-krb5-2 libgssapi3-heimdal libhcrypto4-heimdal
  libheimbase1-heimdal libheimntlm0-heimdal libhx509-5-heimdal libidn11
  libjbig0 libjpeg-turbo8 libjpeg8 libk5crypto3 libkeyutils1
  libkrb5-26-heimdal libkrb5-3 libkrb5support0 libldap-2.4-2 libmysqlclient18
  libpq5 libroken18-heimdal librtmp0 libsasl2-2 libsasl2-modules
  libsasl2-modules-db libtidy-0.99-0 libtiff5 libvpx1 libwind0-heimdal
  libx11-6 libx11-data libxau6 libxcb1 libxdmcp6 libxml2 libxpm4 lsof
  mysql-common openssl php5-cli php5-common php5-json php5-readline psmisc
  sgml-base ssl-cert xml-core
Suggested packages:
  www-browser apache2-doc apache2-suexec-pristine apache2-suexec-custom ufw
  apache2-utils php-pear libgd-tools krb5-doc krb5-user libsasl2-modules-otp
  libsasl2-modules-ldap libsasl2-modules-sql libsasl2-modules-gssapi-mit
  libsasl2-modules-gssapi-heimdal php5-user-cache sgml-base-doc
  openssl-blacklist debhelper
The following NEW packages will be installed:
  apache2 apache2-bin apache2-data ca-certificates curl fontconfig-config
  fonts-dejavu-core krb5-locales libapache2-mod-php5 libapr1 libaprutil1
  libaprutil1-dbd-sqlite3 libaprutil1-ldap libasn1-8-heimdal libcurl3 libedit2
  libfontconfig1 libfreetype6 libgd3 libgssapi-krb5-2 libgssapi3-heimdal
  libhcrypto4-heimdal libheimbase1-heimdal libheimntlm0-heimdal
  libhx509-5-heimdal libidn11 libjbig0 libjpeg-turbo8 libjpeg8 libk5crypto3
  libkeyutils1 libkrb5-26-heimdal libkrb5-3 libkrb5support0 libldap-2.4-2
  libmysqlclient18 libpq5 libroken18-heimdal librtmp0 libsasl2-2
  libsasl2-modules libsasl2-modules-db libtidy-0.99-0 libtiff5 libvpx1
  libwind0-heimdal libx11-6 libx11-data libxau6 libxcb1 libxdmcp6 libxml2
  libxpm4 lsof mysql-common openssl php5 php5-cli php5-common php5-curl
  php5-gd php5-json php5-mysql php5-pgsql php5-readline php5-sqlite php5-tidy
  php5-xdebug psmisc sgml-base ssl-cert xml-core
0 upgraded, 72 newly installed, 0 to remove and 0 not upgraded.
Need to get 14.3 MB of archives.
After this operation, 58.5 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ trusty/main libroken18-heimdal amd64 1.6~git20131207+dfsg-1ubuntu1 [40.0 kB]
[...]
Get:72 http://archive.ubuntu.com/ubuntu/ trusty/main ssl-cert all 1.0.33 [16.6 kB]
Extracting templates from packages: 100%
Preconfiguring packages ...
Fetched 14.3 MB in 1min 4s (223 kB/s)
Selecting previously unselected package libroken18-heimdal:amd64.
(Reading database ... 11527 files and directories currently installed.)
Preparing to unpack .../libroken18-heimdal_1.6~git20131207+dfsg-1ubuntu1_amd64.deb ...
[...]
Unpacking ssl-cert (1.0.33) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up libroken18-heimdal:amd64 (1.6~git20131207+dfsg-1ubuntu1) ...
Setting up libasn1-8-heimdal:amd64 (1.6~git20131207+dfsg-1ubuntu1) ...
[...]
Setting up ssl-cert (1.0.33) ...
Setting up php5-common (5.5.9+dfsg-1ubuntu4.6) ...

Creating config file /etc/php5/mods-available/pdo.ini with new version
php5_invoke: Enable module pdo for cli SAPI
php5_invoke: Enable module pdo for apache2 SAPI

Creating config file /etc/php5/mods-available/opcache.ini with new version
php5_invoke: Enable module opcache for cli SAPI
php5_invoke: Enable module opcache for apache2 SAPI
Setting up php5-curl (5.5.9+dfsg-1ubuntu4.6) ...

Creating config file /etc/php5/mods-available/curl.ini with new version
php5_invoke: Enable module curl for cli SAPI
php5_invoke: Enable module curl for apache2 SAPI
Setting up php5-gd (5.5.9+dfsg-1ubuntu4.6) ...

Creating config file /etc/php5/mods-available/gd.ini with new version
php5_invoke: Enable module gd for cli SAPI
php5_invoke: Enable module gd for apache2 SAPI
Setting up php5-mysql (5.5.9+dfsg-1ubuntu4.6) ...

Creating config file /etc/php5/mods-available/mysql.ini with new version
php5_invoke: Enable module mysql for cli SAPI
php5_invoke: Enable module mysql for apache2 SAPI

Creating config file /etc/php5/mods-available/mysqli.ini with new version
php5_invoke: Enable module mysqli for cli SAPI
php5_invoke: Enable module mysqli for apache2 SAPI

Creating config file /etc/php5/mods-available/pdo_mysql.ini with new version
php5_invoke: Enable module pdo_mysql for cli SAPI
php5_invoke: Enable module pdo_mysql for apache2 SAPI
Setting up php5-pgsql (5.5.9+dfsg-1ubuntu4.6) ...

Creating config file /etc/php5/mods-available/pgsql.ini with new version
php5_invoke: Enable module pgsql for cli SAPI
php5_invoke: Enable module pgsql for apache2 SAPI

Creating config file /etc/php5/mods-available/pdo_pgsql.ini with new version
php5_invoke: Enable module pdo_pgsql for cli SAPI
php5_invoke: Enable module pdo_pgsql for apache2 SAPI
Setting up php5-cli (5.5.9+dfsg-1ubuntu4.6) ...
update-alternatives: using /usr/bin/php5 to provide /usr/bin/php (php) in auto mode

Creating config file /etc/php5/cli/php.ini with new version
php5_invoke mysql: already enabled for cli SAPI
php5_invoke pdo_pgsql: already enabled for cli SAPI
php5_invoke pdo: already enabled for cli SAPI
php5_invoke gd: already enabled for cli SAPI
php5_invoke pgsql: already enabled for cli SAPI
php5_invoke opcache: already enabled for cli SAPI
php5_invoke pdo_mysql: already enabled for cli SAPI
php5_invoke mysqli: already enabled for cli SAPI
php5_invoke curl: already enabled for cli SAPI
Setting up php5-readline (5.5.9+dfsg-1ubuntu4.6) ...

Creating config file /etc/php5/mods-available/readline.ini with new version
php5_invoke: Enable module readline for cli SAPI
php5_invoke: Enable module readline for apache2 SAPI
Setting up php5-sqlite (5.5.9+dfsg-1ubuntu4.6) ...

Creating config file /etc/php5/mods-available/sqlite3.ini with new version
php5_invoke: Enable module sqlite3 for cli SAPI
php5_invoke: Enable module sqlite3 for apache2 SAPI

Creating config file /etc/php5/mods-available/pdo_sqlite.ini with new version
php5_invoke: Enable module pdo_sqlite for cli SAPI
php5_invoke: Enable module pdo_sqlite for apache2 SAPI
Setting up php5-tidy (5.5.9+dfsg-1ubuntu4.6) ...

Creating config file /etc/php5/mods-available/tidy.ini with new version
php5_invoke: Enable module tidy for cli SAPI
php5_invoke: Enable module tidy for apache2 SAPI
Setting up php5-xdebug (2.2.3-2build1) ...
php5_invoke: Enable module xdebug for cli SAPI
php5_invoke: Enable module xdebug for apache2 SAPI
Setting up php5-json (1.3.2-2build1) ...
php5_invoke: Enable module json for cli SAPI
php5_invoke: Enable module json for apache2 SAPI
Processing triggers for ureadahead (0.100.0-16) ...
Setting up libapache2-mod-php5 (5.5.9+dfsg-1ubuntu4.6) ...

Creating config file /etc/php5/apache2/php.ini with new version
php5_invoke readline: already enabled for apache2 SAPI
php5_invoke mysql: already enabled for apache2 SAPI
php5_invoke pdo_pgsql: already enabled for apache2 SAPI
php5_invoke pdo: already enabled for apache2 SAPI
php5_invoke pdo_sqlite: already enabled for apache2 SAPI
php5_invoke gd: already enabled for apache2 SAPI
php5_invoke tidy: already enabled for apache2 SAPI
php5_invoke pgsql: already enabled for apache2 SAPI
php5_invoke sqlite3: already enabled for apache2 SAPI
php5_invoke xdebug: already enabled for apache2 SAPI
php5_invoke opcache: already enabled for apache2 SAPI
php5_invoke pdo_mysql: already enabled for apache2 SAPI
php5_invoke json: already enabled for apache2 SAPI
php5_invoke mysqli: already enabled for apache2 SAPI
php5_invoke curl: already enabled for apache2 SAPI
Module mpm_event disabled.
Enabling module mpm_prefork.
apache2_switch_mpm Switch to prefork
invoke-rc.d: policy-rc.d denied execution of restart.
apache2_invoke: Enable module php5
invoke-rc.d: policy-rc.d denied execution of restart.
Setting up php5 (5.5.9+dfsg-1ubuntu4.6) ...
Processing triggers for libc-bin (2.19-0ubuntu6.5) ...
Processing triggers for ca-certificates (20130906ubuntu2) ...
Updating certificates in /etc/ssl/certs... 164 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d....done.
Processing triggers for sgml-base (1.26+nmu4ubuntu1) ...
 ---> de92584ffd67
Removing intermediate container 4117baf48a8f
Step 2 : WORKDIR /var/www/html
 ---> Running in 792652b2692b
 ---> a62fbc63d764
Removing intermediate container 792652b2692b
Step 3 : ADD composer.* /var/www/html/
 ---> 2fdbef10643a
Removing intermediate container 6c00fd3b177d
Step 4 : RUN curl -s http://getcomposer.org/installer | php &&         php composer.phar install
 ---> Running in 09d1cbf6eb49
#!/usr/bin/env php
All settings correct for using Composer
Downloading...

Composer successfully installed to: /var/www/html/composer.phar
Use it: php composer.phar
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
  - Installing symfony/event-dispatcher (v2.3.2)
    Downloading: connection...    Downloading: 100%

  - Installing symfony/intl (v2.3.2)
    Downloading: connection...    Downloading: 100%

  - Installing symfony/icu (v1.0.0)
    Downloading: connection...    Downloading: 100%

  - Installing symfony/options-resolver (v2.3.2)
    Downloading: connection...    Downloading: 100%

  - Installing symfony/property-access (v2.3.2)
    Downloading: connection...    Downloading: 100%

  - Installing twig/twig (v1.13.2)
    Downloading: connection...    Downloading: 100%

  - Installing twig/extensions (v1.0.0)
    Downloading: connection...    Downloading: 100%

  - Installing symfony/twig-bridge (v2.3.2)
    Downloading: connection...    Downloading: 100%

  - Installing symfony/translation (v2.3.2)
    Downloading: connection...    Downloading: 100%

  - Installing symfony/routing (v2.3.2)
    Downloading: connection...    Downloading: 100%

  - Installing symfony/form (v2.3.2)
    Downloading: connection...    Downloading: 100%

  - Installing symfony/filesystem (v2.3.2)
    Downloading: connection...    Downloading: 100%

  - Installing umpirsky/twig-gettext-extractor (1.1.3)
    Downloading: connection...    Downloading: 100%

symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
symfony/intl suggests installing ext-intl (to use the component with locales other than "en")
symfony/twig-bridge suggests installing symfony/http-kernel ()
symfony/twig-bridge suggests installing symfony/security ()
symfony/twig-bridge suggests installing symfony/templating ()
symfony/twig-bridge suggests installing symfony/yaml ()
symfony/translation suggests installing symfony/config ()
symfony/translation suggests installing symfony/yaml ()
symfony/routing suggests installing doctrine/common ()
symfony/routing suggests installing symfony/config ()
symfony/routing suggests installing symfony/yaml ()
symfony/form suggests installing symfony/http-foundation ()
symfony/form suggests installing symfony/validator ()
Generating autoload files
 ---> 2b2270b16d19
Removing intermediate container 09d1cbf6eb49
Step 5 : ADD . /var/www/html
 ---> 7645347873d2
Removing intermediate container a027c7176a19
Step 6 : RUN chown www-data: -R assets cache db inc/poche install
 ---> Running in 79ce2d68f660
 ---> 741277cd2978
Removing intermediate container 79ce2d68f660
Step 7 : EXPOSE 80
 ---> Running in 5735cd46b438
 ---> c20d2b214a34
Removing intermediate container 5735cd46b438
Step 8 : CMD apache2ctl -DFOREGROUND -e info
 ---> Running in fa59ebf4b483
 ---> d0ec9aecc4b1
Removing intermediate container fa59ebf4b483
Successfully built d0ec9aecc4b1
```

open http://localhost:8080
or (for a mac)
open http://$(boot2docker ip):8080

### CODE REVIEW

**Comment by tcitworld** [comment]
Please have a look at https://registry.hub.docker.com/u/bobmaerten/docker-wallabag/ cc @bobmaerten

**Comment by bobmaerten** [comment]
I said to @nicosomb I'll take a look for 2.x branch into integrating a Dockerfile within the repo [à-la-Gitlab](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/docker/Dockerfile). @jrottenberg approch is quite nice, though it would be preferable starting from [php:apache](https://registry.hub.docker.com/_/php/) in order to be in sync with docker standard baseimages.

**Comment by jrottenberg** [comment]
Ah ! Yeah I saw it, after I've started it, of course ;-)

I'm not a big fan of the phusion approach, I'll look into php:apache, but I'm afraid the benefit of having a php base image will come with the price of having only a selected php modules embedded (https://github.com/docker-library/php/blob/58775aa6924fcb854eb57315f019bbbf729c94d2/5.5/apache/Dockerfile#L51).

I mean, out of the box :

```
  - Installing symfony/form (v2.3.2)
    Downloading: connection...    Downloading: 100%
    Failed to download symfony/form from dist: Could not decompress the archive, enable the PHP zip extension.
A php.ini file does not exist. You will have to create one.
    Now trying to download from source
  - Installing symfony/form (v2.3.2)
    Cloning v2.3.2
```

Your call but it seems to add a lot of complexity for very little value.

**Comment by bobmaerten** [comment]
That's not the way it should be used (docker-php-ext-configure and docker-php-ext-install), but you're probably right about the trouble to achieve prereq state for wallabag.

**Comment by jrottenberg** [comment]
Actually I didn't know about docker-php-ext-install, it's interesting, the final image is bigger : 

     wallabag            latest              9279798c475d        3 minutes ago       565.2 MB

Was 305.5 MB

But it still works, you got the latest/greatest php.

Compare with https://github.com/wallabag/wallabag/pull/1120

**Comment by bobmaerten** [comment]
You're right, docker php image gets to 1Gb after installing wallabag, that's insane!
If you want to lighten final image, you should use debian base image:

    debian                         latest              f6fab3b798be        3 months ago        85.1 MB
    ubuntu                         latest              86ce37374f40        12 weeks ago        192.7 MB

**Comment by jrottenberg** [comment]
Good point, started with debian:jessie

Got final image :
285.2 MB vs 305.5 MB from ubuntu

**Comment by jrottenberg** [comment]
Is there anything else I can add/remove to get it merged ?

Let me know.

**Comment by nicosomb** [comment]
Can you send your PR on dev branch please?

**Comment by jrottenberg** [comment]
I don't believe I can do it through this pull request. I'll close it and open a new one against the dev branch.

**Comment by j0k3r** [comment]
@jrottenberg once a PR is created, you can change the target branch. Yes I know, that's sad

**Pull request closed without merging**
