### PR TITLE
Use IsGranted in SiteCredentialController

### PR DESCRIPTION
**Pull request by yguedidi**
- [x] based on #7375, review only last commit

### CODE REVIEW

**Review by j0k3r — COMMENTED** [review]
Looks ok as well

**Comment by yguedidi** [comment]
@j0k3r sorry for asking review again, seems the workflow keeping the PR in draft so that it's not merged accidentally before rebasing/squashing is not perfect.. I guess you simply can't approve when it's in draft which is expected, but this leads to spamming you, sorry.
should I keep that workflow?

**Comment by j0k3r** [comment]
> should I keep that workflow?

Maybe you can just open a PR and put the _Work in Progress_ label instead of using draft PR?
So if someone approuve the PR, you'll still be able to squash it without losing the approval.

**Review by j0k3r — APPROVED** [review]

**Comment by yguedidi** [comment]
> Maybe you can just open a PR and put the Work in Progress label instead of using draft PR?

@j0k3r this will not protect from an accidental click on merge, but look like to be the best compromise, so OK!

**Pull request merged**
