### PR TITLE
Replace continue; with break; to avoid PHP 7.3 warnings

### PR DESCRIPTION
**Pull request by tcitworld**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| CHANGELOG.md  | no
| License       | MIT

Change `continue` to `break` inside loops for PHP 7.3 compatibility.

### CODE REVIEW

**Comment by j0k3r** [comment]
Do we really need these changes as the build is passing with proxy-manager update?
https://travis-ci.org/wallabag/wallabag/builds/481398975

**Comment by tcitworld** [comment]
It avoids the following [warnings](https://secure.php.net/manual/fr/migration73.incompatible.php#migration73.incompatible.core.continue-targeting-switch)
```
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?
```

**Comment by j0k3r** [comment]
Do we have some of these warnings?

**Comment by j0k3r** [comment]
As far as I can see there is no such warning in recent tests on 2.4: https://travis-ci.org/wallabag/wallabag/jobs/490578426
Two options:
- the code you changed isn't covered by tests, so we need to figure out and apply it
- drop that PR

**Comment by j0k3r** [comment]
The warning only applies to `continue` inside a `switch`. We do not have such case.
Your changes aren't related to `switch` at all :)

But anyway I've added some tests to increase coverage.

**Pull request merged**
