### PR TITLE
Occitan local and French , minor, correction

### PR DESCRIPTION
**Pull request by Quent-in**
| Q             | A
| ------------- | ---
| Bug fix?      | yes|no
| New feature?  | yes|no
| BC breaks?    | yes|no
| Deprecations? | yes|no
| Tests pass?   | yes|no
| Documentation | yes|no
| Translation   | yes|no
| Fixed tickets | comma-separated list of tickets fixed by the PR, if any
| License       | MIT

### CODE REVIEW

**Comment by j0k3r** [comment]
Thanks for that !
But it seems that you use the old file structure for the translation :confused: 
You'll have to update your file to match the new structure otherwise your translation won't be available.

**Comment by Quent-in** [comment]
Old ? I took the files like 4 days ago o_Ô

**Comment by j0k3r** [comment]
We merged the new translation structure 5 days ago #1774

**Comment by Quent-in** [comment]
How did you update the other languages? I'm not doing it manually, clearly.

**Comment by j0k3r** [comment]
I did the update manually :no_mouth:

**Comment by Quent-in** [comment]
Hello you all, you may have guessed that I'm new on GitHub so what I'm about to ask might sound idiot.
I don't get the hang of the milestone-thing :S Is someone working on the structure ? I'd like to know as I really wish to see the new upcoming version of Wallabag with the Occitan language, I have some spare time today so I can see what I can do to help change the files.

**Comment by tcitworld** [comment]
Please come over at https://gitter.im/wallabag/wallabag. I'm not available, but others may be.

**Comment by j0k3r** [comment]
Welcome on Github then ! :wave: 

The defined milestone just indicate that we hope to have this for the upcoming 2.0.0.
To fix you problem, you should close this PR and open a new one from a fresh clone from the v2 branch to get the new translation file structure.

- duplicated the `messages.en.yml` as `messages.oc.yml`
- find the english translation in this new file and replace it by the occitan one

For example, search for _Back to unread articles_ and replace it by _Tornar als pas legits_.
Is that ok for you?

**Comment by Quent-in** [comment]
Crystal clear :) I'll do the job today. Endavant !

**Pull request closed without merging**
