### PR TITLE
fix link to documentation

### PR DESCRIPTION
**Pull request by axelsimon**
fix link to Save your first article (no capital letters in documentation pages)

### CODE REVIEW

**Comment by tcitworld** [comment]
Can this PR can be resent on dev branch ?

**Comment by axelsimon** [comment]
Sure!

**Comment by j0k3r** [comment]
The link `http://doc.wallabag.org/en/User_documentation/save_your_first_article` still doesn't work for me..

**Comment by j0k3r** [comment]
Closed in favor to #1251

**Pull request closed without merging**
