### PR TITLE
Added API endpoint to handle a list of URL

### PR DESCRIPTION
**Pull request by nicosomb**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| Fixed tickets | N/A
| License       | MIT

You can pass an array like this one: 
```
["http://...","http://..."]"
``` 

and add / delete URL in mass.

### CODE REVIEW

**Comment by j0k3r** [comment]
I really think we need to restrict the maximum of urls we can handle.
Otherwise the server might take took long to answer and might even time out.

**Comment by tcitworld** [comment]
I'm not really for this. Deleting an URL should be made through a `DELETE` method, not a `POST` one. You should have a different method to delete a list of urls, and ditch the `action` parameter.

**Comment by nicosomb** [comment]
@j0k3r is that good for you?

**Comment by j0k3r** [comment]
Still needs to restrict limit on number of urls you sent

**Comment by nicosomb** [comment]
@j0k3r I need help for `testLimitBulkAction` please. The Exception seems to be thrown but my test fails.

**Comment by nicosomb** [comment]
Thank you @j0k3r !

**Pull request merged**
