### PR TITLE
Add Thai language

### PR DESCRIPTION
**Pull request by NatJNP**
I add Thai Language.

### CODE REVIEW

**Comment by NatJNP** [comment]
I add all file for Thai Language completion.

**Comment by NatJNP** [comment]
I want to show thai language in  your website. How can i do it?

**Comment by j0k3r** [comment]
Thanks for the new files.
What do you mean by "on your website"? On the documentation? Which website are you talking about?

**Comment by NatJNP** [comment]
Yes i mean all both.

**Comment by nicosomb** [comment]
Today, wa can't easily translate our website (wallabag.org). If you want to translate our documentation, we have a repository https://github.com/wallabag/doc

BTW, thank you so much for your pull request 👍

**Pull request merged**
