### PR TITLE
Renamed Developer section to API client management

### PR DESCRIPTION
**Pull request by nicosomb**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | yes
| Translation   | yes
| Fixed tickets | N/A
| License       | MIT

Just changed the name for Developer section. 
ping @wallabag/translators

### CODE REVIEW

**Comment by justkristin** [comment]
The in-app (iOS) link to "your developer page" must point to the old location, because I get a 404...

**Comment by j0k3r** [comment]
@bourvill ☝️

**Comment by bourvill** [comment]
@j0k3r @justkristin No problem on my device. The link open your name server setting with url of developer page.

What your version of wallabag server?

**Comment by nicosomb** [comment]
@justkristin what is the wrong URL please?

**Pull request merged**
