### PR TITLE
Fixes mailto link in documentation

### PR DESCRIPTION
**Pull request by cstuder**
| Q             | A
| ------------- | ---
| Bug fix?      | yes|
| New feature?  | no|
| BC breaks?    | no|
| Deprecations? | no|
| Tests pass?   | yes|
| Documentation | yes|
| Translation   | yes|
| Fixed tickets |-
| License       | MIT

No functional changes.

### CODE REVIEW

**Comment by nicosomb** [comment]
Thank you!
Can you fix the french and german documentation too please?

**Comment by cstuder** [comment]
Done.

**Comment by nicosomb** [comment]
👍

**Comment by j0k3r** [comment]
:+1:

**Pull request merged**
