### PR TITLE
Split symfony/symfony

### PR DESCRIPTION
**Pull request by yguedidi**
I hope I missed nothing, at least tests pass

### CODE REVIEW

**Comment by Kdecherf** [comment]
Should we target milestone 2.7 for this PR? @wallabag/core @yguedidi

**Comment by yguedidi** [comment]
To me it's a dependency refactoring, so it could fit in 2.6, but up to you :)

**Comment by Kdecherf** [comment]
> To me it's a dependency refactoring, so it could fit in 2.6, but up to you :)

Fine with it, will review it and target 2.6.3 then. Thanks

**Review by Kdecherf — APPROVED** [review]
Looks good, could you rebase?

**Comment by yguedidi** [comment]
Thanks! Sure I will in about 30min

**Comment by yguedidi** [comment]
@Kdecherf rebased on latest master

**Review by nicosomb — APPROVED** [review]

**Pull request merged**
