### PR TITLE
Update fr_FR.utf8.po

### PR DESCRIPTION
**Pull request by goofy-bz**
formulation (trivial)

### CODE REVIEW

**Comment by tcitworld** [comment]
The .mo file should have been updated too.

**Comment by goofy-bz** [comment]
> The .mo file should have been updated too.
.po and .mo just suck :P — we translator want .properties! (but JSON will do)
http://www.lafermeduweb.net/billet/l20n-un-framework-de-traduction-avance-pour-le-web-par-mozilla-1791.html

**Comment by tcitworld** [comment]
Ohhh. :D  Thanks for the link.

**Comment by tcitworld** [comment]
And that went directly into master, @nicosomb ! I guess we're really tired. ^^

**Comment by nicosomb** [comment]
:+1: thank you for the link ... And yes, we are tired :-D

**Pull request merged**
