### PR TITLE
Use FQCN as service name

### PR DESCRIPTION
**Pull request by yguedidi**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | depends on the policy
| Deprecations? | yes
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| CHANGELOG.md  | no
| License       | MIT

- [x] to update after 2.5.0 release
- [x] wait for #5761 and #5810 to be merged

Prepare for use of autowiring in order to remove more depreciations by using contructor/action dependency injection

### CODE REVIEW

**Comment by yguedidi** [comment]
@j0k3r @Kdecherf didn't know what to answer to the BC break point... what id the policy?
if wallabag aim to be extended by custom code, then this is a BC break for those who have made use of internal services.
but if it's considered an end product as is, then it's not :)

**Review by nicosomb — APPROVED** [review]
oh yes! thank you @yguedidi. Seems ok to me.

**Comment by yguedidi** [comment]
@nicosomb you're welcome! :slightly_smiling_face:

**Review by Kdecherf — APPROVED** [review]
Tests are green, looks good :+1:

**Review by Kdecherf — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Comment by yguedidi** [comment]
@nicosomb @Kdecherf @j0k3r updated on latest 2.6.0 branch, mainly apply the change to the recently introduced Delicious support.
remaining named services are the ones about Redis and AMQP, as they all use the same base class with different configuration

**Comment by yguedidi** [comment]
> Should we really keep all these commits? Couldn't squash some of them?

@j0k3r really up to you! me I tend to always prefer small and atomic commits as they facilitate code review and help fixing any review feedback.
I squashed all the import services in a single commit and repository also, hope it fits your needs.
BTW, I also updated on latest 2.6.0 and did the addition fixes as #5838 introduced one usage of TagRepository

**Pull request merged**
