### PR TITLE
Documentation on how to configure mobile apps to work with wallabag.it

### PR DESCRIPTION
**Pull request by Zettt**
See issue #2765.

### CODE REVIEW

**Comment by j0k3r** [comment]
From where did you get that iOS screenshot? It doesn't look like the official iOS app.

**Comment by Zettt** [comment]
It isn't, but the official iOS app, apparently, doesn't want to have anything to do with wallabag itself. Therefore I figured it's irrelevant where the screenshot comes from. The screenshot is from Wallabag Pro.

**Comment by j0k3r** [comment]
> It isn't, but the official iOS app, apparently, doesn't want to have anything to do with wallabag itself. 

Following your reflexion, Wallabag Pro should be handled in the same way. So we won't have to put Wallabag Pro screenshot in the doc :thinking: 

Well I don't agree about _the "official iOS app" to have anything to do with wallabag itself_.

The problem you are encountered is related to Wallabag Pro, not wallabag itself, nor wallabag.it, nor the official iOS app. So it have nothing to do in the official documentation.

If we have to define something in the doc, I think it's preferable to be oriented with official app. We won't put a screenshot for all app which use wallabag. It'll be a mess. Just think if Twitter put screenshot of each app on the way to connect to Twitter using an app? :flushed: No way.

So I think the best solution is to put a screenshot of the official app **as an example**.

Also, there shouldn't be a mention to wallabag.it in the official wallabag doc. It should just be called "wallabag" instead.

**Comment by Zettt** [comment]
So you are saying it's better to make instructions with three screenshots, instead of one, although the information those three screenshots display are the same as this one screenshot?

**Comment by nicosomb** [comment]
Hello @Zettt ! 

@j0k3r said that we only put documentation about our iOS official application. If you update your screenshots with our iOS application, we can merge your PR.

**Comment by Zettt** [comment]
@nicosomb I've deleted the screenshot now. I don't know how this now works. Do I need to send another PR?

**Comment by nicosomb** [comment]
@bourvill Is this documentation correct?

**Comment by bourvill** [comment]
Sound like good.

Maybe squash this pr ?

**Pull request merged**
