### PR TITLE
Log an error level message when user auth fail

### PR DESCRIPTION
**Pull request by j0k3r**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | kind of
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | maybe with a custom config of fail2ban
| Translation   | no
| Fixed tickets | https://github.com/wallabag/wallabag/issues/3183
| License       | MIT

When a user login using the form we know log an error level information with information about the user:
- username used
- IP
- User agent

For example:

> Authentication failure for user "eza", from IP "127.0.0.1", with UA: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36".

It’ll allows server admin using fail2ban to configure it to block these people if they generate too much failure authentication.

poke @lapineige @maniackcrudelis @JimboJoe
Let me know if it's ok for you.

### CODE REVIEW

**Comment by j0k3r** [comment]
I won't add a custom test because it's nearly impossible to check the logger from a functional test (apart from reading the whole log file and check that it contains something).

**Comment by aaa2000** [comment]
Is there a reason not to use a listener on `security.authentication.failure` or `security.interactive_login` event ? http://symfony.com/doc/current/components/security/authentication.html#authentication-events

**Comment by j0k3r** [comment]
I first though about a listener then I discovered the `failure_handler` option.
Maybe it's better to use a listener. At least it should be more easy to test.

**Comment by tcitworld** [comment]
What about API auth ?

**Comment by nicosomb** [comment]
I'm surprised that this log is not already there in symfony authentication.

**Comment by j0k3r** [comment]
@nicosomb it logs a debug message by default with "Authentication failure, forward/redirect triggered."

**Comment by nicosomb** [comment]
Thank you for this idea and this PR. fail2ban will be well configured on wallabag.it soon thanks to you 👍

**Comment by j0k3r** [comment]
@tcitworld I though about that too. But it doesn't seems to have events fired when auth fail..

https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/blob/master/Controller/TokenController.php

**Comment by tcitworld** [comment]
Yeah, and overloading the controller is out of scope for now. Many things should be improved on FOSOAuthBundle :/

**Comment by j0k3r** [comment]
@tcitworld https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/issues/245 might be a start.
But it seems there are a lot of PR opened on that repo and few people handling them.

**Comment by tcitworld** [comment]
Yeah, I know.

**Comment by nicosomb** [comment]
Don't forget documentation. Or just open a issue in the repo.

**Comment by lapineige** [comment]
> Thank you for this idea and this PR. fail2ban will be well configured on wallabag.it soon thanks to you :+1:

I was sure this would be useful outside of Yunohost ^^

Thanks a lot @j0k3r for the PR :)

**Pull request merged**
