### PR TITLE
V2 improve view

### PR DESCRIPTION
**Pull request by modos189**
| Q             | A
| ------------- | ---
| Bug fix?      |  partially
| New feature?  | yes
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| Fixed tickets | #1877 
| License       | MIT

### CODE REVIEW

**Comment by tcitworld** [comment]
Can you add a screenshot too ?

**Comment by modos189** [comment]
**Before**
Firefox:
screenshot_20160825_164937
Qupzilla:
screenshot_20160825_165002
Chrome:
screenshot_20160825_165024


**After**
Firefox:
screenshot_20160825_163123
Qupzilla:
screenshot_20160825_163427
Chrome:
screenshot_20160825_163459

**Comment by tcitworld** [comment]
Will test on mobile view but for now it can go. :+1:

**Comment by tcitworld** [comment]
:+1:

**Comment by modos189** [comment]
Also, i created a repository plugin tinydot to npm:
https://www.npmjs.com/package/jquery.tinydot

**Pull request merged**
