### PR TITLE
[#1590] Add JSON import from wallabag v2

### PR DESCRIPTION
**Pull request by nicosomb**
Add #1590

TODO

* [ ] remove duplicated code from v1 importer
* ~~add XML/CSV imports~~ (not in this PR)

### CODE REVIEW

**Comment by j0k3r** [comment]
> remove duplicated code from v1 importer
You mean, inside the controller ?

**Comment by nicosomb** [comment]
yes

**Comment by nicosomb** [comment]
When you'll have time, can you have a look on this PR please?

**Comment by tcitworld** [comment]
We're good to close #1600 ?

**Comment by nicosomb** [comment]
Im' not sure. Will retry

**Pull request merged**
