### PR TITLE
Mark as mobile app capable

### PR DESCRIPTION
**Pull request by nicofrand**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| Fixed tickets | 
| License       | MIT

This will allow wallabag web-app to be added to the homescreen on smartphones, without the URL bar etc.. so that is acts more like a real application.

### CODE REVIEW

**Comment by tcitworld** [comment]
Better to add a manifest.json file : https://developer.chrome.com/multidevice/android/installtohomescreen#supporting

**Comment by nicofrand** [comment]
I am fine with both even if mobile-app-capable is the shortest solution when not providing different icons etc.

Why would you close the PR though ? Start a review or something so that I can modify it. That really doesn't encourage to contribute anymore.

**Comment by tcitworld** [comment]
Sorry, my comment was a bit harsh, you're welcomed to open another pull request or an issue directly. I just closed because this change is of no use if we have a manifest.json file.

**Comment by nicofrand** [comment]
I don't see any manifest.json anywhere in the repository ?

**Comment by tcitworld** [comment]
I was planning to add it (or to review a PR ;-) )

**Pull request closed without merging**
