### PR TITLE
Add PHP 7.2 compatibility

### PR DESCRIPTION
**Pull request by j0k3r**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| CHANGELOG.md  | yes
| Fixed tickets | #...
| License       | MIT

Just update few things to make Travis build run PHP 7.2 properly. We'll see later to fix issue.

First issue found:

```
contentthis
is
my
contentthis
is
my
content</p>' contains "this is my content".

/Users/j0k/Sites/github/wallabag/tests/Wallabag/CoreBundle/Helper/ContentProxyTest.php:410
```

### CODE REVIEW

**Comment by j0k3r** [comment]
Hum that `ContentProxyTest` issue in test seems to be related to a new version of tidy. :confused:

**Comment by j0k3r** [comment]
Nightly build is fixed as well :tada:

**Comment by nicosomb** [comment]
Do we need to merge this PR in `2.4` branch?

**Comment by j0k3r** [comment]
I don't think so since I only updated tests. Code was already compatible with PHP 7.2 :+1:

**Pull request merged**
