### PR TITLE
Create index.rst

### PR DESCRIPTION
**Pull request by araujo0205**

### CODE REVIEW

**Comment by nicosomb** [comment]
Thank you for your help.
Can I merge or do you want to translate the other pages now ?

**Comment by araujo0205** [comment]
I will translate other page later. You can merge. 
Another thing, I make the config file for new Site, imasters.com.br. Where I send ? ( I using 1.9.1)
Sorry for my bad English :)

**Comment by nicosomb** [comment]
Will merge.
About config file, ping @j0k3r 



Le 19 janv. 2016 20:20, à 20:20, araujo0205 <notifications@github.com> a écrit:

**Comment by j0k3r** [comment]
@araujo0205 Send it to https://github.com/fivefilters/ftr-site-config

**Comment by nicosomb** [comment]
Translation available here: http://wallabag.readthedocs.org/pt/v2/

**Comment by araujo0205** [comment]
Great, Thanks.

**Pull request merged**
