### PR TITLE
Changed reading_time field to prevent null values

### PR DESCRIPTION
**Pull request by nicosomb**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes 🤞 
| Documentation | no
| Translation   | no
| Fixed tickets | #3286
| License       | MIT

Not sure about Postgres migration. I don't install PG on my new laptop, so if someone can help me here 😗 ...

### CODE REVIEW

**Comment by Kdecherf** [comment]
There's a chance that migration on PostgreSQL will eventually fail:
```
You can only use SET NOT NULL when the column contains no null values.
```

You may need to add an additional statement before the `ALTER TABLE` to update field `reading_time` for all rows with `null` value.

**Comment by nicosomb** [comment]
Something like my last commit?

**Comment by j0k3r** [comment]
I think so

**Comment by Kdecherf** [comment]
Seems ok :+1:

**Comment by Kdecherf** [comment]
Another note but I'm unsure: as long as you don't define any default value, any future `INSERT` in this table will need to explicitly provide a value for `reading_time`.

**Comment by j0k3r** [comment]
This is the default value: https://github.com/wallabag/wallabag/pull/3373/files#diff-a7f29fe65dccca2b9551e2380b1a9340R187

**Pull request merged**
