### PR TITLE
Update composer

### PR DESCRIPTION
**Pull request by j0k3r**
_I'l rebase this branch when this PR #1035 will be merged_

It's better to use tagged version in composer (at least from my POV), it ease the download since it can download a zip file instead of cloning the project.

Do you really need the master of `simplepie/simplepie` ? Or the 1.3.1 branch is enough ?

You should tag your own libraries / fork:

 - wallabag/PHP-Flash-Messages
 - wallabag/kriss_php5
 - wallabag/pagination
 - wallabag/PHPePub
 - wallabag/php-readability
 - wallabag/phpMobi
 - wallabag/Fivefilters_Libraries

### CODE REVIEW

**Comment by nicosomb** [comment]
About simplepie, 1.3.1 seems to be enough.
I plan to tag our libraries. Thank you for your advices !

**Comment by j0k3r** [comment]
@nicosomb good to merge :)

**Comment by nicosomb** [comment]
For my own libraries, I just need to create branch, like I did here: https://github.com/wallabag/Fivefilters_Libraries/ ?

**Comment by tcitworld** [comment]
Tags is better than branches, right ?

**Comment by j0k3r** [comment]
A tag is different than a branch :)
For your own librairies, you just need to create a tag on the HEAD of the master branch. It's really easy to do that using Github!

**Comment by nicosomb** [comment]
I merge this PR and will open a new one with changes on our own libraries.

**Comment by tcitworld** [comment]
It may have been better to keep the version number of the original versions, what do you think ?

**Comment by j0k3r** [comment]
I agree with @tcitworld, could be better for every one if you keep the original version instead of tagging 1.0.0.

**Comment by nicosomb** [comment]
:+1:

**Comment by nicosomb** [comment]
But many of libraries don't have original version. That's why I tagged 1.0.0.

**Comment by nicosomb** [comment]
I'm sure I don't do like I have to. What is the right process?

**Comment by tcitworld** [comment]
> But many of libraries don't have original version. That's why I tagged 1.0.0.
Indeed. Let's leave it this way then (or just call master branch).

**Pull request merged**
