### PR TITLE
Mark all imported articles as read

### LINKED ISSUE #870: Mark all imported articles as read
When importing a batch of articles from a file, you may not want to set all of them as "read" manually. So a checkbox in the import screen would be nice.

### PR DESCRIPTION
**Pull request by tcitworld**
Fix #870

### CODE REVIEW

**Comment by nicosomb** [comment]
Nice!

**Comment by tcitworld** [comment]
It doesn't do Pocket, but I assume it's normal.

**Comment by j0k3r** [comment]
Good idea !

- [ ] Missing french translation
- [ ] Missing tests
- [ ] Missing Pocket

**Comment by tcitworld** [comment]
How can the tests to be sure the inserted articles are really archived for v2 & Pocket be made ?

**Comment by j0k3r** [comment]
It can't. Or at least, you need to check before the import that the article is not archived and check after the import.

**Comment by tcitworld** [comment]
> you need to check before the import that the article is not archived

By parsing the json file inside the test once before ?

**Comment by j0k3r** [comment]
Or just by knowing that an url will be imported

**Comment by nicosomb** [comment]
@tcitworld It seems that your PR has tests. What is your todo list here?

**Comment by j0k3r** [comment]
@tcitworld poke

**Comment by tcitworld** [comment]
Yeah, I'll need a little help on that. ;-)

**Comment by j0k3r** [comment]
Excellent, what kind of help?

**Pull request merged**
