### PR TITLE
Upgrade to Symfony 3.2

### PR DESCRIPTION
**Pull request by nicosomb**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| Fixed tickets | N/A
| License       | MIT

Upgrade to Symfony 3.2

### CODE REVIEW

**Comment by nicosomb** [comment]
Failed builds seem to be related to https://github.com/symfony/symfony/issues/19532 but on Travis we have PHPUnit 5.6.5.

**Comment by j0k3r** [comment]
We should include PHPUnit in our deps.
But since we are still supporting PHP 5.5, we can't use the latest version of PHPUnit in our composer.json (because it doesn't support PHP 5.5).

We should wait until the 2.3.0 when we'll drop PHP 5.5 support

**Comment by nicosomb** [comment]
Maybe not in 2.2 branch. 
What do you think?

**Comment by j0k3r** [comment]
I'm ok with that.
There is no revolution in 3.2 and BC is kept.
Also, it'll allow to fine tune some code with 3.2 improve in minor version of 2.2

**Comment by j0k3r** [comment]
Don't merge it right now.
LiipThemeBundle is broken with Symfony 3.2.1 :disappointed: 
https://github.com/liip/LiipThemeBundle/issues/157

**Pull request merged**
