### PR TITLE
[WIP] fosoauth

### PR DESCRIPTION
**Pull request by nicosomb**

### CODE REVIEW

**Comment by j0k3r** [comment]
Why did you come back on fosuser 1.3 when you jumped to 2.0 because of a (I can't remember which one) bug ?

**Comment by nicosomb** [comment]
I can't remember the bug. 
Why 1.3? If we want to use sonata admin and sonata user (why not?), we need fosuser 1.3 (I lost my wednesday afternoon at work due to this problem)...

**Comment by j0k3r** [comment]
On Gitter, you told me about that issue: https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1800

**Comment by nicosomb** [comment]
You're right.. But I can't reproduce it at the moment ...

**Pull request closed without merging**
