### PR TITLE
Remove transitive dependencies

### PR DESCRIPTION
**Pull request by yguedidi**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| CHANGELOG.md  | no
| License       | MIT

Have the code rely on transitive dependencies (dependencies not explicitly required) is not good, as their versioning is not managed by us.

This PR remove relying on transitive dependencies by requiring them explicitly at their installed minor version from composer.lock.
Transitive dependencies are identified with [ComposerRequireChecker](https://github.com/maglnet/ComposerRequireChecker)

Here the result on current 2.6.0 branch (d510dc6c98afcf1a178d878d08e371f4f68d158a):

```
The following 44 unknown symbols were found:
+--------------------------------------------------------+--------------------+
| Unknown Symbol                                         | Guessed Dependency |
+--------------------------------------------------------+--------------------+
| DAMA\DoctrineTestBundle\DAMADoctrineTestBundle         |                    |
| Datetime                                               |                    |
| Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle  |                    |
| Doctrine\Bundle\FixturesBundle\Fixture                 |                    |
| Doctrine\Common\Collections\ArrayCollection            |                    |
| Doctrine\Common\DataFixtures\DependentFixtureInterface |                    |
| Doctrine\Common\EventSubscriber                        |                    |
| Doctrine\Common\Persistence\ManagerRegistry            |                    |
| Doctrine\DBAL\Exception\DriverException                |                    |
| Doctrine\DBAL\Platforms\SqlitePlatform                 |                    |
| Doctrine\DBAL\Schema\Schema                            |                    |
| Doctrine\Migrations\AbstractMigration                  |                    |
| Doctrine\Persistence\ObjectManager                     |                    |
| FILTER_VALIDATE_INT                                    | ext-filter         |
| filter_var                                             | ext-filter         |
| GuzzleHttp\Psr7\Uri                                    |                    |
| GuzzleHttp\Psr7\UriResolver                            |                    |
| Hateoas\Configuration\Route                            |                    |
| Hateoas\Representation\Factory\PagerfantaFactory       |                    |
| Http\Client\Common\HttpMethodsClient                   |                    |
| Http\Client\Common\PluginClient                        |                    |
| Http\Client\Common\Plugin\ErrorPlugin                  |                    |
| Http\Client\Exception\RequestException                 |                    |
| Http\Client\HttpClient                                 |                    |
| Http\Discovery\MessageFactoryDiscovery                 |                    |
| Http\Message\MessageFactory                            |                    |
| Imagick                                                | ext-imagick        |
| JMS\Serializer\SerializationContext                    |                    |
| JMS\Serializer\SerializerBuilder                       |                    |
| MOBIFile                                               |                    |
| PhpAmqpLib\Message\AMQPMessage                         |                    |
| Psr\Http\Message\ResponseInterface                     |                    |
| Psr\Log\LoggerAwareInterface                           |                    |
| Psr\Log\LoggerInterface                                |                    |
| Psr\Log\NullLogger                                     |                    |
| RulerZ\RulerZ                                          |                    |
| Swift_Mailer                                           |                    |
| Swift_Message                                          |                    |
| Symfony\Bundle\MakerBundle\MakerBundle                 |                    |
| Twig\Environment                                       |                    |
| Twig\Extension\AbstractExtension                       |                    |
| Twig\Extension\GlobalsInterface                        |                    |
| Twig\TwigFilter                                        |                    |
| Twig\TwigFunction                                      |                    |
+--------------------------------------------------------+--------------------+
```

Here the result after this PR:

```
The following 9 unknown symbols were found:
+--------------------------------------------------------+--------------------+
| Unknown Symbol                                         | Guessed Dependency |
+--------------------------------------------------------+--------------------+
| DAMA\DoctrineTestBundle\DAMADoctrineTestBundle         |                    |
| Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle  |                    |
| Doctrine\Bundle\FixturesBundle\Fixture                 |                    |
| Doctrine\Common\DataFixtures\DependentFixtureInterface |                    |
| Imagick                                                | ext-imagick        |
| MOBIFile                                               |                    |
| Swift_Mailer                                           |                    |
| Swift_Message                                          |                    |
| Symfony\Bundle\MakerBundle\MakerBundle                 |                    |
+--------------------------------------------------------+--------------------+
```

- [x] to update after 2.5.0 release
- [x] wait for #5761 and #5810 to be merged

Remaining unknown symbols are the ones:
- that are used by tests and dev only
- that are optional (Imagisk)
- that not namespaced (MOBIFile and Swiftmailer) but those are required explicitly already (maybe a bug in the tool with not namespaced classes)

### CODE REVIEW

**Comment by yguedidi** [comment]
@Kdecherf @nicosomb @j0k3r this is ready to be merged! I think it should be merged first, then I'll rebase #5782, then #5759, and we'll be done with my PRs updating composer.lock haha

**Comment by yguedidi** [comment]
and here the dependencies update detail:

| Production Changes                   | From    | To      | Compare                                                                              |
|--------------------------------------|---------|---------|--------------------------------------------------------------------------------------|
| doctrine/cache                       | 1.12.1  | 1.13.0  | [...](https://github.com/doctrine/cache/compare/1.12.1...1.13.0)                     |
| doctrine/reflection                  | 1.2.2   | 1.2.3   | [...](https://github.com/doctrine/reflection/compare/1.2.2...1.2.3)                  |
| egulias/email-validator              | 3.1.2   | 3.2     | [...](https://github.com/egulias/EmailValidator/compare/3.1.2...3.2)                 |
| incenteev/composer-parameter-handler | v2.1.4  | v2.1.5  | [...](https://github.com/Incenteev/ParameterHandler/compare/v2.1.4...v2.1.5)         |
| j0k3r/graby-site-config              | 1.0.150 | 1.0.152 | [...](https://github.com/j0k3r/graby-site-config/compare/1.0.150...1.0.152)          |
| php-http/discovery                   | 1.14.1  | 1.14.2  | [...](https://github.com/php-http/discovery/compare/1.14.1...1.14.2)                 |
| symfony/http-client                  | v5.4.8  | v5.4.9  | [...](https://github.com/symfony/http-client/compare/v5.4.8...v5.4.9)                |
| symfony/polyfill-apcu                | v1.25.0 | v1.26.0 | [...](https://github.com/symfony/polyfill-apcu/compare/v1.25.0...v1.26.0)            |
| symfony/polyfill-ctype               | v1.25.0 | v1.26.0 | [...](https://github.com/symfony/polyfill-ctype/compare/v1.25.0...v1.26.0)           |
| symfony/polyfill-iconv               | v1.25.0 | v1.26.0 | [...](https://github.com/symfony/polyfill-iconv/compare/v1.25.0...v1.26.0)           |
| symfony/polyfill-intl-icu            | v1.25.0 | v1.26.0 | [...](https://github.com/symfony/polyfill-intl-icu/compare/v1.25.0...v1.26.0)        |
| symfony/polyfill-intl-idn            | v1.25.0 | v1.26.0 | [...](https://github.com/symfony/polyfill-intl-idn/compare/v1.25.0...v1.26.0)        |
| symfony/polyfill-intl-normalizer     | v1.25.0 | v1.26.0 | [...](https://github.com/symfony/polyfill-intl-normalizer/compare/v1.25.0...v1.26.0) |
| symfony/polyfill-mbstring            | v1.25.0 | v1.26.0 | [...](https://github.com/symfony/polyfill-mbstring/compare/v1.25.0...v1.26.0)        |
| symfony/polyfill-php72               | v1.25.0 | v1.26.0 | [...](https://github.com/symfony/polyfill-php72/compare/v1.25.0...v1.26.0)           |
| symfony/polyfill-php73               | v1.25.0 | v1.26.0 | [...](https://github.com/symfony/polyfill-php73/compare/v1.25.0...v1.26.0)           |
| symfony/polyfill-php80               | v1.25.0 | v1.26.0 | [...](https://github.com/symfony/polyfill-php80/compare/v1.25.0...v1.26.0)           |
| symfony/polyfill-uuid                | v1.25.0 | v1.26.0 | [...](https://github.com/symfony/polyfill-uuid/compare/v1.25.0...v1.26.0)            |

| Dev Changes            | From    | To      | Compare                                                                  |
|------------------------|---------|---------|--------------------------------------------------------------------------|
| nikic/php-parser       | v4.13.2 | v4.14.0 | [...](https://github.com/nikic/PHP-Parser/compare/v4.13.2...v4.14.0)     |
| symfony/phpunit-bridge | v6.0.8  | v6.1.0  | [...](https://github.com/symfony/phpunit-bridge/compare/v6.0.8...v6.1.0) |

**Comment by j0k3r** [comment]
I just merged master into the 2.6.0 branch

**Comment by yguedidi** [comment]
@j0k3r @nicosomb @Kdecherf I'm back! sorry for my absence! I managed to update this, next one is #5782 after this is merged

**Review by Kdecherf — APPROVED** [review]

**Comment by j0k3r** [comment]
Do we really need 22 commits for changing 2 files?

**Comment by yguedidi** [comment]
@j0k3r "need" I would say no, I made it this way to isolate each update.
I can squash to one commit if you prefer

**Comment by Kdecherf** [comment]
@yguedidi you can squash all commits changing composer files, I'll merge after that

**Comment by yguedidi** [comment]
@Kdecherf done

**Comment by Kdecherf** [comment]
Thanks @yguedidi :+1:

**Pull request merged**
