### PR TITLE
Run tests on an uptodate HHVM

### PR DESCRIPTION
**Pull request by j0k3r**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| Fixed tickets | 
| License       | MIT

Related: https://github.com/symfony/symfony/pull/18947/files

### CODE REVIEW

**Comment by nicosomb** [comment]
@j0k3r what are the steps to finish this PR?

**Comment by j0k3r** [comment]
As soon as https://github.com/wallabag/wallabag/pull/2095 will ok and merged, I'll rebase this PR and see what could left to do.

**Comment by nicosomb** [comment]
:+1:

**Comment by tcitworld** [comment]
:+1:

**Comment by tcitworld** [comment]
:+1:

**Pull request merged**
