### PR TITLE
Add box.json to compile wallabag PHAR

### PR DESCRIPTION
**Pull request by Dialga**
Add initial box.json to compile wallabag into a single compressed PHAR using Box.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes/no
| Documentation | yes/no
| Translation   | no
| CHANGELOG.md  | no
| License       | MIT

### CODE REVIEW

**Comment by j0k3r** [comment]
Why not.
But as you said _initial_ does that mean it can be improved?

**Comment by Dialga** [comment]
> Why not.
> But as you said _initial_ does that mean it can be improved?

Yes, since I am not entirely familiar with wallabag's internals this first step does produce a .phar.

**Comment by j0k3r** [comment]
OK then can you work on your own fork to build the phar using that initial `box.json` and once it's seems pretty ok to you, can you update the PR?
Also, could you please add information in the PR on how can we test that phar generation using that file.
Thanks

**Comment by nicosomb** [comment]
@Dialga do you plan to work on this PR?

**Comment by Dialga** [comment]
Sorry no, I've lost interest in this.

**Pull request closed without merging**
