### PR TITLE
fix #1371 config screen: display bug in RSS tab

### LINKED ISSUE #1371: Display issues in config screen
There is a strange display in configuration view: 
- "Rss token VS. token string
- "Rss links" VS. "Unread"

capture d ecran 2015-08-19 a 01 34 47

Moreover "Rss" should be written in caps.
And why not using "favourites" instead of "fav"?
Why mandatory fields are not indicated with a specific character (i.e. *)?

Tested on v2.wallabag.org with Firefox.

### PR DESCRIPTION
**Pull request by nicosomb**
It's not the better display (because I use h5 ..) but it's better than before.

### CODE REVIEW

**Comment by j0k3r** [comment]
Shouldn't we try to fix that by using some CSS instead of using `h5`?

**Comment by nicosomb** [comment]
I was in my train, and h5 was the easiest solution.

**Comment by j0k3r** [comment]
So now, since you aren't in the train, you can find a better solution :)

**Comment by nicosomb** [comment]
@modos189 If you can help me here, I prefer let you do it.

**Comment by modos189** [comment]
I can not offer anything but to use css

**Comment by j0k3r** [comment]
Fixed:

image

**Comment by modos189** [comment]
I like)

**Pull request merged**
