### PR TITLE
V2 material

### PR DESCRIPTION
**Pull request by modos189**

### CODE REVIEW

**Comment by nicosomb** [comment]
Nice! :+1:

**Comment by modos189** [comment]
I had to remove the F-Droid and the Diaspora, because did not find any icon-font in which they are present. Create my own font dared not =)

**Comment by tcitworld** [comment]
We'll need to separate the Firefox Browser Icon & the Firefox OS app.

**Comment by modos189** [comment]
Hmm ... they have the same logo)

**Comment by tcitworld** [comment]
> Create my own font dared not =)

You can put custom icons for once too. :)

**Comment by nicosomb** [comment]
Can we merge or do you need to wait for custom icons?

**Comment by modos189** [comment]
Merge

**Pull request merged**
