### PR TITLE
add option "Japanese(日本語)"

### PR DESCRIPTION
**Pull request by AKKED**
add option "Japanese(日本語)"

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | no
| Documentation | no
| Translation   | yes
| CHANGELOG.md  | no
| License       | MIT

### CODE REVIEW

**Comment by Kdecherf** [comment]
Hello @AKKED,

Could you merge all your PR in a single PR for simplicity and clarity?

**Comment by AKKED** [comment]
> 
> 
> Hello @AKKED,
> 
> Could you merge all your PR in a single PR for simplicity and clarity?

I'm sorry.
Is this all right? ( https://github.com/wallabag/wallabag/pull/4274 )
I'm a beginner, so I might be doing something wrong. Let me know if you're wrong.

**Comment by Rurik19** [comment]
Hello [@AKKED ](https://github.com/AKKED)
It would be great if you make the Japanese translation also for our browser extension for wallabag - [Wallabagger](https://github.com/wallabag/wallabagger)!

**Comment by AKKED** [comment]
> 
> 
> Hello [@AKKED ](https://github.com/AKKED)
> It would be great if you make the Japanese translation also for our browser extension for wallabag - [Wallabagger](https://github.com/wallabag/wallabagger)!

Hello @Rurik19 
Wallabagger translation is complete. Is [this](https://github.com/wallabag/wallabagger/pull/192) all right?
Please tell me if anything is wrong.

**Pull request closed without merging**
