### PR TITLE
Add original link in public view of the article

### PR DESCRIPTION
**Pull request by nicosomb**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| Fixed tickets | N/A
| License       | MIT

capture d ecran 2016-08-25 a 14 40 56

### CODE REVIEW

**Comment by j0k3r** [comment]
:+1:

**Comment by tcitworld** [comment]
No need for *Original article*, what do you think ?

**Comment by nicosomb** [comment]
@tcitworld removed.

**Comment by tcitworld** [comment]
Please update screenshot (yup, totally no time to checkout).

**Comment by nicosomb** [comment]
capture d ecran 2016-08-25 a 15 35 22

**Comment by tcitworld** [comment]
Maybe put the link on the left instead of center ?

**Comment by tcitworld** [comment]
:+1:

**Pull request merged**
