### PR TITLE
Fix project version in installation command

### PR DESCRIPTION
**Pull request by lologhi**

### CODE REVIEW

**Comment by nicosomb** [comment]
Hello @lologhi !

Why do you force to alpha-2? With our command, we don't need to change our README for each new alpha ;-)

**Comment by lologhi** [comment]
Hello :)
It's because previous command was not working for me : 

```
composer create-project wallabag/wallabag wallabag 2.0.*@alpha
zsh: no matches found: 2.0.*@alpha
```

**Comment by nicosomb** [comment]
Can you try `composer create-project wallabag/wallabag wallabag "2.0.*@alpha"`?

**Comment by lologhi** [comment]
Yep, better !

```
composer create-project wallabag/wallabag wallabag "2.0.*@alpha"
Installing wallabag/wallabag (2.0.0-alpha.2)
  - Installing wallabag/wallabag (2.0.0-alpha.2)
    Loading from cache
```

It's only me? Ot do I update my PR?

**Comment by nicosomb** [comment]
You can update your PR please.

**Comment by lologhi** [comment]
Ok, done

**Comment by nicosomb** [comment]
Can you rebase your PR, because I merged an other PR and there are conflicts.

**Comment by j0k3r** [comment]
:+1:

**Comment by lologhi** [comment]
I don't know where to help with my small Sf2 knowledge? You have some easy issues I could try to fix? Thx !

**Comment by nicosomb** [comment]
We have https://github.com/wallabag/wallabag/issues?q=is%3Aopen+is%3Aissue+label%3A%22Easy+bug%22 and some bugs here https://github.com/wallabag/wallabag/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.0.0-beta.1

**Pull request merged**
