### PR TITLE
implement FosUser

### PR DESCRIPTION
**Pull request by nicosomb**

### CODE REVIEW

**Comment by nicosomb** [comment]
The implementation is over, I have a problem with unit test. I have to work on it.

**Comment by j0k3r** [comment]
@nicosomb did you have any idea or idea how to fix them?

**Comment by nicosomb** [comment]
No idea. 

Here is the error: 
```
1) Wallabag\CoreBundle\Tests\Command\InstallCommandTest::testRunInstallCommandNoInteraction
Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO wallabag_user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, name, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["test", "test", "test", "test", 1, "56fv16uilvcw048sowwwkc80ksswggc", "ed46db72cb4931aab07242b32b328218b8362941", null, 0, 0, null, null, null, "a:0:{}", 0, null, null, "2015-09-10 11:13:00", "2015-09-10 11:13:00"]:

SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: wallabag_user.email_canonical
``` 

But I don't have user with this email in my test database. 

As I told on gitter few weeks ago, maybe the problem comes from sqlite https://laracasts.com/discuss/channels/general-discussion/testdummy-and-codeception-with-sqlite-in-memory-error-integrity-constraint-19

Will try with mysql (already tried, but few weeks ago ... I forgot what I did).

**Comment by j0k3r** [comment]
It wasn't related to the database.

I guess it is the FOSUser implementation that failed the test. It tried to create a new user with a username that already exist in the database. As I said in the commit message, _We assume that the install command must be run to initialize a wallabag instance. NEVER to add more user._ Did you agree?

**Comment by nicosomb** [comment]
oooh yes, you're right!

**Comment by j0k3r** [comment]
@nicosomb :warning: :warning: be careful when you rebase a branch, you lost my commit here ..
I've pushed it again.

**Comment by nicosomb** [comment]
How can I do that?


-------- Message d'origine --------
De : Jeremy Benoist <notifications@github.com>
Envoyé : 12 septembre 2015 11:37:15 UTC+02:00
À : wallabag/wallabag <wallabag@noreply.github.com>
Cc : "Nicolas Lœuillet" <nicolas@loeuillet.org>
Objet : Re: [wallabag] implement FosUser (#1362)

@nicosomb :warning: :warning: be careful when you rebase a branch, you lost my commit here ..
I've pushed it again.

---

**Comment by j0k3r** [comment]
I don't really know ..

**Comment by nicosomb** [comment]
can we merge now?

**Comment by nicosomb** [comment]
(I know. I think I didn't do `git pull origin v2-fosuser`)

**Comment by j0k3r** [comment]
Yep good to merge. Then we'll have to work on oAuth PR

**Comment by nicosomb** [comment]
Finally merged :)

**Pull request merged**
