### PR TITLE
Update messages.es.yml

### PR DESCRIPTION
**Pull request by jami7**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | no
| Documentation | no
| Translation   | yeS
| Fixed tickets | comma-separated list of tickets fixed by the PR, if any
| License       | MIT

### CODE REVIEW

**Comment by nicosomb** [comment]
Hello! 

It seems you have a useless space here: 

```
     client:
```

**Comment by jami7** [comment]
Is that line 356?

**Comment by nicosomb** [comment]
Yes

**Comment by tcitworld** [comment]
The PR was closed because we renamed branch `v2` to `master`. Please send your PR again.

**Comment by jami7** [comment]
Okay, not sure how to pul up the file again though. I can find it but then
it doesn't allow me to edit. Can you guide me please? I'm pressing all
kinds of buttons. I used to just go to:

https://github.com/wallabag/wallabag/tree/v2/src/Wallabag/CoreBundle/Resources/translations

but now I'm lost.

Sorry for the delay in the PR again...

jami

**Comment by tcitworld** [comment]
Keep calm. I'll email you tomorrow with a how-to. ;-)

**Comment by jami7** [comment]
Thanks, Thomas ;)

**Comment by jami7** [comment]
Hey, Thomas-

I know you're busy, but any guidance for me for the new PR? I think I found
how to change the v2 branch to master for my default. Then I think I
resubmitted the PR. Am I good now? Should I continue on with the other
files for translation?

Thanks,
jami

**Pull request closed without merging**
