### PR TITLE
Replace wallabag's fork of tcpdf with the original one, PHP 7.4 support

### PR DESCRIPTION
**Pull request by Kdecherf**
| Q             | A
| ------------- | ---
| Bug fix?      | ~
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| CHANGELOG.md  | no
| License       | MIT

This PR replaces our fork of TCPDF with the original version and fixes some issues seen with PHP 7.4.

Note: I currently use the `master` version of Graby to run the tests, we may need to release a new version to include the change for the TCPDF dependency. (cc @j0k3r)

### CODE REVIEW

**Comment by j0k3r** [comment]
What about https://github.com/wallabag/TCPDF/commit/15c4364246914d216d066d29e89b85527bcc9d8c &
https://github.com/wallabag/TCPDF/commit/10b560fa4b805d618f1a71e95d8940feb7737659 ?

Does these fixes are included in the upstream changes?

**Comment by Kdecherf** [comment]
The first change is fixed in upstream since the version 6.2.13, see https://github.com/tecnickcom/TCPDF/commit/751d6c97fe369da6a7b00d5a6002a8ae47a45618

However the second one is missing.

**Comment by nicosomb** [comment]
Why do we need to update PocketController for this PR?

**Comment by Kdecherf** [comment]
@nicosomb Tests were failing with this file on PHP 7.4

**Comment by Kdecherf** [comment]
@j0k3r regarding https://github.com/wallabag/wallabag/issues/2776, the issue does not occur with tecnickcom/tcpdf 6.3.5. So I think we're good to go with the switch without the missing change.

**Pull request merged**
