### PR TITLE
Prepare wallabag 2.0.5

### PR DESCRIPTION
**Pull request by nicosomb**
Prepare 2.0.5

https://github.com/wallabag/wallabag/compare/2.0.4...master

### CODE REVIEW

**Comment by j0k3r** [comment]
:+1:

**Comment by nicosomb** [comment]
I will probably release 2.0.5 this evening or tomorrow.

**Comment by j0k3r** [comment]
Well I still think it's valuable to add the diff when you prepare a release: https://github.com/wallabag/wallabag/compare/2.0.4...master

**Comment by nicosomb** [comment]
OK, I thought I forgot a link in my 1st post, that's why I removed it.

**Pull request merged**
