### PR TITLE
Add german translation.

### PR DESCRIPTION
**Pull request by jlnostr**

### CODE REVIEW

**Comment by nicosomb** [comment]
Nice. Can you also change config.yml please? 
https://github.com/wallabag/wallabag/blob/v2/app/config/config.yml#L28

**Comment by jlnostr** [comment]
Done :)

**Comment by j0k3r** [comment]
Thanks a ton for that. Could you keep the translation up to date until the final release?

**Comment by jlnostr** [comment]
Shouldn't be a problem :)

**Comment by nicosomb** [comment]
@j0k3r Can we merge or we let this PR open till the final release?

**Comment by j0k3r** [comment]
You can merge

**Pull request merged**
