### PR TITLE
Bigger image preview in case of only image content

### LINKED ISSUE #1770: Generate thumbnails for image-only content
I am very happy to see that bagging images (png/jpg files) works with v2. But testing revealed that there is no thumbnail generated like with text articles that contain image.

bildschirmfoto von 2016-03-09 08-23-31

bildschirmfoto von 2016-03-09 08-23-42
### Environment
- wallabag version: v2 beta 1
- How did you install wallabag?  shared hosting complete package
- OS: centos 
- type of hosting: shared hosting
- which storage system: sqlite (default)
### Steps to reproduce/test case

Bag this link: http://satwcomic.com/art/sheepish-food-cravings.png

If you bag the article containing the link thumbnail generation works. But not if only one image.

Works: http://satwcomic.com/women-around-the-world
## Expected behaviour

Show thumbnails for image-only content. 

Name the bagged item  "Image: filename.png"

Expected result similar to this:
bildschirmfoto von 2016-03-09 08-32-58

- [ ] make the image clickable
- [ ] then, remove the useless title
- [ ] but keep the domain name

### PR DESCRIPTION
**Pull request by j0k3r**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| Fixed tickets | fix #1770
| License       | MIT

Display a bigger image in case of image content
If the content is only an image, we can display a bigger preview image because we won’t have text to display.

Preview (first card is image content only, then regular content, then content without preview):

image

Also:
- split different card view to avoid too much complexity in the `entries.html.twig`
- Remove the left margin of tag (you can see on the third card of the screenshot)
- Add `grunt watch` task

Improvement (I failed to do it...) :
- make the image clickable
- then, remove the useless title
- but keep the domain name

### CODE REVIEW

**Comment by nicosomb** [comment]
👍 

So what about

> * make the image clickable
> * then, remove the useless title
> * but keep the domain name

Do you want help in this PR or do we plan to do this later?

**Comment by j0k3r** [comment]
If anyone want to give a try :)
I didn't succeed.

**Comment by tcitworld** [comment]
Will handle if you can wait tomorrow.

**Comment by j0k3r** [comment]
@tcitworld did you got time to fix it?
Otherwise I think we can merge it and improve it later.

**Comment by tcitworld** [comment]
Yup. I leave the issue open.

**Pull request merged**
