### PR TITLE
Better public sharing page

### PR DESCRIPTION
**Pull request by j0k3r**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | improvement
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | needed (ping @wallabag/translators)
| Fixed tickets | https://github.com/wallabag/wallabag/issues/3034
| License       | MIT

I’ve increase the width of the page 900px, 600px looks too small for me. Should we use something like 90% instead?

Before:
image

After:
image

### CODE REVIEW

**Comment by jlnostr** [comment]
I'm not sure about this change. The 600px version looks far more readable. In my opinion there are too many words on a single line - it's hard to read that. Maybe increasing the font size can help.

**Comment by j0k3r** [comment]
You mean, keep 900px and increase font size?

**Comment by jlnostr** [comment]
Yeah, also I think the line-height could be increased a bit. If wanted, you can make use of the template [I use for the windows app](https://github.com/wallabag/windows-app/tree/master/src/wallabag.UWP/Assets/Article). Got a lot of positive feedback for it.

**Comment by nicosomb** [comment]
Agree with 600px.

@jlnostr @Strubbl @matteocoder  we need your help to translate strings.

**Comment by matteocoder** [comment]
shared_by_wallabag: "Questo articolo è stato condiviso da %username% con <a href='%wallabag_instance%'>wallabag</a>"

**Comment by j0k3r** [comment]
Before the @jlnostr css:

image

And after, I must admit, it's more easier to read with that version:

image

**Comment by tcitworld** [comment]
Yeah. Especially like the quote style.

**Comment by j0k3r** [comment]
@tcitworld I need your help on the webpack part.
I created `/app/Resources/static/themes/_global/share.scss` but I don't know how to use it in the twig template then.
Could you fix it? 🙂

**Comment by tcitworld** [comment]
Fixed and rebased.

**Pull request merged**
