### PR TITLE
[WIP] filter by creation date

### PR DESCRIPTION
**Pull request by nicosomb**
TODO:
* ~~test~~
* if one field is not filled with the good format => error (in fact, it's the same thing for the reading time filter)
* ~~smart calendar (hi @modos189)~~ done in an other PR.

### CODE REVIEW

**Comment by modos189** [comment]
By the way, nice to show above the list of articles, which filters are applied

**Comment by nicosomb** [comment]
Yes, good idea. Can you implement it?

**Comment by modos189** [comment]
I do not know how to do it :(

**Comment by nicosomb** [comment]
I'll have a look. Priority is to the opened PR #1337 ;-)

**Pull request merged**
