### PR TITLE
Add activation of 'rewrite' mod of Apache

### PR DESCRIPTION
**Pull request by qtheuret**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | no
| Documentation | yes
| Translation   | yes/no
| Fixed tickets | #...
| License       | MIT

Add activation of 'rewrite' mod of Apache.

I let you do modifications for Italian and German documentations.

### CODE REVIEW

**Comment by tcitworld** [comment]
ping @wallabag/translators

**Comment by matteocoder** [comment]
Can I post the translation here instead of opening a separate PR?

**Comment by nicosomb** [comment]
@matteocoder yes you can post here.

**Comment by matteocoder** [comment]
Non dimenticate di attivare la mod *rewrite* di Apache

.. code-block:: bash

    a2enmod rewrite && systemctl reload apache2

Here it is. Also, shouldn't be it "activate" instead of "active"?

**Comment by tcitworld** [comment]
Indeed.

**Comment by jlnostr** [comment]
And the german translation:

```
Vergiss nicht, die *rewrite* mod von Apache zu aktivieren.

.. code-block:: bash 
a2enmod rewrite && systemctl reload apache2
```

**Comment by Quent-in** [comment]
Oblidetz pas d'activar lo mòde *rewrite* d'Apache.
.. code-block:: bash
a2enmod rewrite && systemctl reload apache2

For the occitan locale :)

**Comment by nicosomb** [comment]
@Quent-in Thanks but the documentation is not translated in occitan ;-)

**Pull request merged**
