### PR TITLE
fix link to documentation

### PR DESCRIPTION
**Pull request by axelsimon**
fix link to Save your first article (no capital letters in documentation pages)

### CODE REVIEW

**Comment by j0k3r** [comment]
The link `http://doc.wallabag.org/en/User_documentation/save_your_first_article` still doesn't work for me..

**Comment by nicosomb** [comment]
The good one is `http://doc.wallabag.org/en/User/save_your_first_article.html`

**Comment by j0k3r** [comment]
@axelsimon Could you update the url with the good one please? So we can merge this PR :) Thanks

**Comment by nicosomb** [comment]
Raaah, I thought my commit will be embedded. I fix that now.

**Comment by nicosomb** [comment]
It's good in fact. Yeah.

**Pull request merged**
