### PR TITLE
rename Tags entity

### PR DESCRIPTION
**Pull request by nicosomb**

### CODE REVIEW

**Comment by j0k3r** [comment]
Why do you remove the TagEntries?

**Comment by nicosomb** [comment]
It's my fault... I'll push it.

Le 6 février 2015 22:54:52 UTC+01:00, Jeremy <notifications@github.com> a écrit :
>Why do you remove the TagEntries?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/wallabag/wallabag/pull/1063#issuecomment-73319741

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by j0k3r** [comment]
I've no-idea :) Maybe you can squash your commit to have a clean log.

**Comment by nicosomb** [comment]
squashed.

**Comment by j0k3r** [comment]
Well, same question again, why do you remove the TagEntries? :)

**Comment by nicosomb** [comment]
Oh I thought I repushed it.

**Comment by nicosomb** [comment]
File restored.

**Pull request merged**
