### PR TITLE
Fixed last merge who caused CSS/JS bugs

### PR DESCRIPTION
**Pull request by nicosomb**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| Fixed tickets | 
| License       | MIT

Last merge from master to 2.1 was buggy. 
I just need help, because jquery.tinydot from @modos189 doesn't seem to be loaded. 

Help needed @modos189 @tcitworld @j0k3r :)

### CODE REVIEW

**Comment by j0k3r** [comment]
My bad if it was buggy. Mostly because stuff has to be done to include new lib in package.json as soon as they are added in the master branch.
And this PR is related to https://github.com/wallabag/wallabag/issues/2249

**Comment by nicosomb** [comment]
@j0k3r not a problem 😗

**Comment by j0k3r** [comment]
jquery.tinydot is now loaded for material.

**Comment by tcitworld** [comment]
Instead of concating jquery.tinydot, require it through browserify in the main js file.

**Comment by nicosomb** [comment]
👍

**Comment by nicosomb** [comment]
> Instead of concating jquery.tinydot, require it through browserify in the main js file.

@tcitworld why?

**Comment by tcitworld** [comment]
Because I find it better to use js modules instead of just concat all code. Moreover, minification *should* be better.

**Comment by j0k3r** [comment]
@tcitworld tried both `require('tinydot');` 

>> Error: Cannot find module 'jQuery' from '/home/jeremy/github/wallabag/node_modules/jquery.tinydot/src'

`require('jquery.tinydot');`

>> Error: Cannot find module 'tinydot' from '/home/jeremy/github/wallabag/web/bundles/wallabagcore'

Without success.

**Comment by j0k3r** [comment]
It looks too complex to load a jquery plugin with requirejs...
I think we'll keep it like this. I'll switch to the non minified version instead.

**Comment by tcitworld** [comment]
> It looks too complex to load a jquery plugin with requirejs...

I'll have a look.

**Pull request merged**
