### PR TITLE
Improvement view

### PR DESCRIPTION
**Pull request by modos189**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Deprecations? | yes
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| License       | MIT

Improved side menu, reduced the font size on small screens, fixed a form to add links on small screens

screenshot_20161013_140150
screenshot_20161013_140217

---

screenshot_20161013_141020
screenshot_20161013_141849

---

screenshot_20161013_143831
screenshot_20161013_143844

---

Before:
screenshot_20161014-235003
screenshot_20161014-235007

After:
screenshot_20161015-003244
screenshot_20161015-003252

### CODE REVIEW

**Comment by tcitworld** [comment]
Why is there @nicosomb commit hère ?

**Comment by modos189** [comment]
I don't know)

**Comment by nicosomb** [comment]
Nice improvements. 

About the commit, it's because you created your branch from the 2.1.1 tag, not from master branch. You need to do `git checkout -b yourbranch origin/master`, then `git cherry-pick e47a9093406065ef55bfe073e2edb336b4102a3c` and push your new branch.

**Comment by nicosomb** [comment]
See #2450.

**Comment by tcitworld** [comment]
@modos189 Could you push changes on branches on the wallabag repo so that everyone has access to them ?

**Comment by modos189** [comment]
@tcitworld i do not undestand, what should I do?)

**Comment by tcitworld** [comment]
Next time you submit a PR, push the branch directly on the wallabag repo, not your own. :-)
You should have write access on it.

**Comment by modos189** [comment]
Thanks)

**Pull request closed without merging**
