### PR TITLE
Disable zappr approvals

### PR DESCRIPTION
**Pull request by j0k3r**
We are going to use the built-in function by Github (while waiting for "review" to be part of zappr)

### CODE REVIEW

**Comment by j0k3r** [comment]
Disabled at Zappr config (https://zappr.opensource.zalan.do/repository/wallabag/wallabag) instead.

**Comment by tcitworld** [comment]
Well, it could be removed from this file too. I'm for reopening.

**Comment by j0k3r** [comment]
As soon as webhook for review will be available zappr will merge both thing. So, commenting with :+1: will put an approval review and vice versa.

**Comment by tcitworld** [comment]
Oh, did Github mention webhooks for review ?

**Comment by j0k3r** [comment]
Not yet.
https://github.com/zalando/zappr/issues/442

**Pull request closed without merging**
