### PR TITLE
UI Changes

### PR DESCRIPTION
**Pull request by tcitworld**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | no |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Documentation | no |
| Translation | no |
| Fixed tickets | #2307 |
| License | MIT |

<hr>

Reduced margins on extremely tight mobile view
capture d ecran 2016-10-16 a 11 48 46

---- 

- Use 4 entries on big desktop display
- Reduce picture size
- Change reading time & original domain position
  selection_005

----

- Changed a bit tools on entry page
- increased page title
  selection_006

----

  (with more tags)
  selection_007

### CODE REVIEW

**Comment by pmichelazzo** [comment]
Something that I would like to see changed on the desktop interface is another paginator below the articles. I always need to roll up the screen to go to another page.

Best

**Comment by nicosomb** [comment]
> Something that I would like to see changed on the desktop interface is another paginator below the articles. I always need to roll up the screen to go to another page.

It's a bug. This paginator was present, before.

**Comment by j0k3r** [comment]
What's left to be done here?

**Comment by tcitworld** [comment]
Fix the pagination bug, the issues mentioned above and https://github.com/wallabag/wallabag/issues/2478

**Comment by j0k3r** [comment]
Bottom pagination re-added

**Comment by nicosomb** [comment]
With big titles, I've got a problem like this:

**Comment by nicosomb** [comment]
do you need help for this PR?

**Comment by tcitworld** [comment]
- [ ] Fix #2515

**Comment by tcitworld** [comment]
> With big titles, I've got a problem like this

@nicosomb What's the screen resolution ?

**Comment by nicosomb** [comment]
@tcitworld 1440 x 900

**Comment by tcitworld** [comment]
Please test again.

**Comment by nicosomb** [comment]
It looks better 👍  yeah!

**Pull request merged**
