### PR TITLE
translate documentation to German

### PR DESCRIPTION
**Pull request by Strubbl**
| Q             | A
| ------------- | ---
| Bug fix?      | |no
| New feature?  | |no
| BC breaks?    | |no
| Deprecations? | |no
| Tests pass?   | |no
| Documentation | yes|no
| Translation   | yes|no
| Fixed tickets | comma-separated list of tickets fixed by the PR, if any
| License       | MIT

### CODE REVIEW

**Comment by tcitworld** [comment]
Thanks ! Can you squash your commits a bit ?

**Comment by Strubbl** [comment]
I think github provides the feature of squashing the whole PR in one commit when accepting? That's what i would do anyways.

**Comment by tcitworld** [comment]
I've heard it was doing it in a dirty way, so one of us has disabled this feature.

**Comment by Strubbl** [comment]
okay, I am going to squash!

**Comment by j0k3r** [comment]
Wow thanks for that awesome work 👍

**Pull request merged**
