### PR TITLE
Portuguese (Brazilian) translation

### PR DESCRIPTION
**Pull request by pmichelazzo**
This the Portuguese (Brazilian) for the Wallaby v2.

### CODE REVIEW

**Comment by nicosomb** [comment]
Hello @pmichelazzo! 

Thanks for this translation. 

Can you have a look here http://doc.wallabag.org/en/master/developer/translate.html please? 
We need to change other files for a new translation ;-)

**Comment by pmichelazzo** [comment]
Hi @nicosomb,

Is just the config.yml right?
May I work on the documentation translation on the next few days?

Best

**Comment by nicosomb** [comment]
Yes, it's just the config.yml

About the translation of the documentation, why not. But I will ping you each time we update the documentation, be careful ;-)

**Comment by pmichelazzo** [comment]
It's done. Go ahead with the merge.

Regards

**Comment by j0k3r** [comment]
@pmichelazzo thanks for that. Could you please tick the checkbox on your PR to "Allow edits from maintainers" ? ([see doc here](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/)).
So I can push some fixes on your PR.

Thanks

**Comment by pmichelazzo** [comment]
@j0k3r , I'm sorry, my bad. 

It's checked now.
Best

**Comment by j0k3r** [comment]
No problem, I'll fixes tonight.

**Comment by pmichelazzo** [comment]
Ok, great!

**Comment by j0k3r** [comment]
@pmichelazzo I've pushed my changes.
You'll notice in my [last commit](https://github.com/wallabag/wallabag/pull/2473/commits/1cad9416c9fda6a99aa03213844341c20bb84518) some string to translate. It seems that you took files from an old version so some string were missing.

You just need to translate them and replace the `# ` (note the space after the `#`) before each line.

**Comment by pmichelazzo** [comment]
Hey @j0k3r,

Now you have just uncommented lines ;)

Cheers

**Comment by j0k3r** [comment]
This is great !
I missed one translation at line 147 `number_of_tags`. After that one we'll be able to merge it :)

**Comment by pmichelazzo** [comment]
Hi @j0k3r, it's done!

**Comment by nicosomb** [comment]
Thank you!

**Comment by j0k3r** [comment]
Thanks !

**Pull request merged**
