### PR TITLE
Fix #1603: Enhance requirements in InstallCommand

### LINKED ISSUE #1603: [v2] Source code should not contain TODO comments - in src/Wallabag/…/Command/InstallCommand.php, line 67
**[in src/Wallabag/CoreBundle/Command/InstallCommand.php, line 67](https://github.com/wallabag/wallabag/blob/d481f42b7d383eb6211d1d3049d1a2c8288d9edb/src/Wallabag/CoreBundle/Command/InstallCommand.php#L67)**

> TODO comments are left in the code when a feature (or a bug) isn't completely developed (or fixed). You should complete the implementation and remove the comment.

```php
    {
        $this->defaultOutput->writeln('<info><comment>Step 1 of 4.</comment> Checking system requirements.</info>');

        $fulfilled = true;

        // @TODO: find a better way to check requirements
        $label = '<comment>PCRE</comment>';
        if (extension_loaded('pcre')) {
            $status = '<info>OK!</info>';
            $help = '';
        } else {
```

### PR DESCRIPTION
**Pull request by nicosomb**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| Fixed tickets | #1603
| License       | MIT

### CODE REVIEW

**Comment by j0k3r** [comment]
I think we should go further than that and re-check all requirements from the v1 and re-include them (if they are pertinent) to this checkup.

**Comment by nicosomb** [comment]
https://github.com/wallabag/wallabag/blob/master/install/install_functions.php ?

**Comment by j0k3r** [comment]
Yeah sth like that.

**Comment by j0k3r** [comment]
Looks good to me.
We'll see if we still need to check for `curl_*` function.

**Pull request merged**
