### PR TITLE
add exif requirement for phpEpub & update SF files

### PR DESCRIPTION
**Pull request by tcitworld**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| Fixed tickets | 
| License       | MIT

### CODE REVIEW

**Comment by j0k3r** [comment]
It doesn't look recent this change: https://github.com/Grandt/PHPePub/search?utf8=%E2%9C%93&q=exif&type=Code
Do we really need it or is it related to an issue?

**Comment by tcitworld** [comment]
Well, it's the first time I've encountered it. The `exif_imagetype` wasn't defined. And there was also https://github.com/Grandt/PHPePub/issues/37

**Comment by j0k3r** [comment]
I think we do not have to add this requirement.
I guess it more a bug on PHPePub side.

Before this commit, check was done on exif extension: https://github.com/Grandt/PHPePub/commit/7606182da6d74592346f1df2e4d40f5b4b275578#diff-738d6dc186ddd5f8e5366f4bef5652b0L644
But now, it checks about GD: https://github.com/Grandt/PHPePub/blob/7606182da6d74592346f1df2e4d40f5b4b275578/src/PHPePub/Helpers/ImageHelper.php#L256-L259

There is something wrong here. It shouldn't check for GD but for Exif instead. You should better send a PR to fix that.

**Comment by tcitworld** [comment]
https://github.com/Grandt/PHPePub/pull/38

**Pull request closed without merging**
