### PR TITLE
🐛 — Fix duplicated icons on "Search engine" and "new link" forms

### LINKED ISSUE #4130: "Search engine" and "new link" forms are broken
### Issue details

See this screenshot (firefox or chrome, macos) : 

Capture d’écran 2019-09-27 à 16 38 50

We have too many icons 😉 

### Environment

* wallabag version (or git revision) that exhibits the issue: master
* How did you install wallabag? git clone
* Last wallabag version that did not exhibit the issue (if applicable):
* php version: 7.2
* OS: macos
* type of hosting (shared or dedicated): localhost
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): mysql

### PR DESCRIPTION
**Pull request by ldidry**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| CHANGELOG.md  | no
| License       | MIT

Fixes #4130 

Fix duplicated icons on "Search engine" and "new link" forms

### CODE REVIEW

**Comment by j0k3r** [comment]
Any chance to share a screenshot?

**Comment by ldidry** [comment]
Sure.

Screenshot_2019-10-09_Pour_bien_débuter_–_wallabag(1)
Screenshot_2019-10-09_Pour_bien_débuter_–_wallabag

**Comment by ldidry** [comment]
(sorry, I have "Dark reader" extension that darkify all the website I go on, that’s why the screenshots are dark)

**Comment by ldidry** [comment]
Sure, but hey, the text in the `<i>` tags wasn’t translated first :wink:

**Comment by nicosomb** [comment]
> the text in the <i> tags wasn’t translated first

It's because it's not a displayed text: it's used by the CSS library to display an icon.

**Pull request merged**
