### PR TITLE
Version 1.9.0

### PR DESCRIPTION
**Pull request by tcitworld**
Changes in brief : 
* PDF and Mobi Export 
* Build-in offline documentation
* Evernote, Carrot, Diaspora sharing buttons
* Random article
* Refetch Article
* Import tags
* Tag an article when saving it
* deleted broken courgette theme
* new installer (much more checkings, should avoid most common errors)
* public registration
* email at new user to confirm his new account
* updated translations
* many improvements and bugs corrected

### CODE REVIEW

**Comment by nicosomb** [comment]
I'll try it tomorrow or tuesday

**Comment by tcitworld** [comment]
Made you [a nice zip](https://github.com/wallabag/wallabag/releases/tag/1.9beta) and everything. :)

**Comment by nicosomb** [comment]
We have to change the random feature, and let SQL do the random. 

All seems good for me! 

I'll try an update.

**Comment by tcitworld** [comment]
> I'll try an update. 

There are also some changes here. :)

**Comment by nicosomb** [comment]
> There are also some changes here. :)

What are the changes? 

I copied / pasted files, it works :+1:

**Comment by tcitworld** [comment]
> What are the changes?

> I copied / pasted files, it works :+1: 

Autodelete of install directory.

**Comment by nicosomb** [comment]
Nice !

**Comment by marienfressinaud** [comment]
:+1:

**Pull request merged**
