### PR TITLE
Pagination improved

### PR DESCRIPTION
**Pull request by Simounet**
Hello there,
I fixed a wrong behavior when the pagination was on in the list mode. I improved the pagination handling (bigger space on small screens) and fixed the wrong page number alignment.
wallabag-pagination-before
wallabag-pagination-after

### CODE REVIEW

**Comment by nicosomb** [comment]
👍 
It seems that your PR fixes https://github.com/wallabag/wallabag/issues/3457.

**Comment by nicosomb** [comment]
About the desktop view, all is still OK with your changes?

**Comment by Simounet** [comment]
Yep, I checked both views on desktop and mobile.

**Comment by Simounet** [comment]
If you want. I thought about it but I didn't modified it. What's the point of living this theme around? I know you might have good memories with it but it's not so handy to maintain multiple officials themes. It might deserves another topic.

**Comment by j0k3r** [comment]
I don't know, maybe we can then say "hey you can switch to a different theme" :slightly_smiling_face: 
+1 for an other topic

**Pull request merged**
