### PR TITLE
Feature display items number

### PR DESCRIPTION
**Pull request by nicosomb**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| Fixed tickets | comma-separated list of tickets fixed by the PR, if any
| License       | MIT

Added #1789 

capture d ecran 2016-04-21 a 22 25 37

I was wrong in #1963 (wrong destination branch. If only github lets me change the branch...)

### CODE REVIEW

**Comment by j0k3r** [comment]
Rebased ✅

**Comment by nicosomb** [comment]
I added cache for these queries. 
Do you think it's better?
Where can I store the value for cache lifetime (here, 5)?

**Comment by j0k3r** [comment]
You can define it in the config.yml and then inject this parameter for the service `@wallabag_core.entry_repository` using a call method like `setLifeTime` and in the repository you can define a default value for lifetime which will be used when we don't retrieve the repo using the container.
You get it?

**Comment by nicosomb** [comment]
Yes, it seems to be OK. 

Do my changes about cache seem good for you?

**Comment by j0k3r** [comment]
Yup, looks ok

**Comment by j0k3r** [comment]
👍

**Comment by tcitworld** [comment]
We should mention in the administrator documentation to use cache services (Memcache, APC...).

**Pull request merged**
