### PR TITLE
Updated composer.lock

### PR DESCRIPTION
**Pull request by bdunogier**
> Updates `composer.lock`.

Had to restrict scheb/two-factor-bundle to ~1.4.0 because of a circular service reference.
See https://github.com/scheb/two-factor-bundle/issues/33.

### CODE REVIEW

**Comment by j0k3r** [comment]
Oh yes, Rulerz now requires PHP 5.5, could you update Travis & composer.json with that information?

**Comment by bdunogier** [comment]
> Oh yes, Rulerz now requires PHP 5.5, could you update Travis & composer.json with that information?

Sure.

**Comment by j0k3r** [comment]
You forgot to remove PHP 5.4 from .travis.yml file :)

**Comment by j0k3r** [comment]
:+1:

**Pull request merged**
