### PR TITLE
Dropping PHP 5.5

### PR DESCRIPTION
**Pull request by j0k3r**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | yes
| Documentation | yes
| Translation   | no
| Fixed tickets | #2594
| License       | MIT

- [x] we might update doc about PHP support

### CODE REVIEW

**Comment by nicosomb** [comment]
Only doc is missing here?

**Comment by j0k3r** [comment]
I guess

**Comment by nicosomb** [comment]
Done. 
I don't know if we need to change other parts of the documentation.

**Comment by j0k3r** [comment]
I don't know too but it's ok for me.
We'll see later what we can improve from using PHP 5.6 now

**Pull request merged**
