### PR TITLE
public assets files removed from webpack

### PR DESCRIPTION
**Pull request by Simounet**
We don't need these files from `_global` to be directly accessible. They are imported into themes files and never used by the browser.

### CODE REVIEW

**Comment by j0k3r** [comment]
I'm wondering if it's not used when user share an entry?

**Comment by j0k3r** [comment]
https://github.com/wallabag/wallabag/blob/master/src/Wallabag/CoreBundle/Resources/views/themes/common/Entry/share.html.twig#L20-L24

**Comment by Simounet** [comment]
You got me! I didn't think about this part. I will change that.

**Review by 0098912200770 — APPROVED** [review]

**Comment by 0098912200770** [comment]
My wallet account send tanks

در تاریخ پنجشنبه ۲۶ نوامبر ۲۰۲۰،‏ ۰۸:۲۹ Jérémy Benoist <
notifications@github.com> نوشت:

**Review by j0k3r — APPROVED** [review]

**Pull request merged**
