### PR TITLE
Fix PATCH method

### PR DESCRIPTION
**Pull request by j0k3r**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| Fixed tickets | https://github.com/wallabag/wallabag/issues/3249 & https://github.com/wallabag/wallabag/issues/3232
| License       | MIT

The PATCH method for the entry should only update what user sent to us and not the whole entry as it was before. (https://github.com/wallabag/wallabag/issues/3249)

Also, sending tags when patching an entry will now remove all current tags & assocatied new ones. (https://github.com/wallabag/wallabag/issues/3232)

### CODE REVIEW

**Comment by nicosomb** [comment]
@Rurik19 @Simounet don't hesitate to give your opinion here ;-)

**Comment by Simounet** [comment]
I'm sorry but I up to date with the 2.3, cleared the cache and I'm still encountering this issue:
```
[2017-07-05 22:53:38] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: DateTime::__construct() expects parameter 1 to be string, object given" at /wallabag/src/Wallabag/CoreBundle/Helper/ContentProxy.php line 133 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: DateTime::__construct() expects parameter 1 to be string, object given at /wallabag/src/Wallabag/CoreBundle/Helper/ContentProxy.php:133)"} []
```

**Comment by j0k3r** [comment]
When patching the entry?
I do not have the problem anymore.
Could you remove the entry and try again?

**Comment by Simounet** [comment]
You can close this one. I made a new PR (#3280) about this issue.

**Pull request merged**
