### PR TITLE
Update messages.es.yml

### PR DESCRIPTION
**Pull request by jami7**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | no
| Documentation | no
| Translation   | yes
| Fixed tickets | comma-separated list of tickets fixed by the PR, if any
| License       | MIT

### CODE REVIEW

**Comment by j0k3r** [comment]
Why did you submit so many PR?
It's better to do everything in one PR ..

**Comment by nicosomb** [comment]
This one is useless, I close it. 

And as @j0k3r said, it's better to send a single PR ;-)

**Comment by jami7** [comment]
Ok thank you. I sometimes don't really understand how the PR works so I'm learning as I go. Thought I needed to a PR after every set of changes so that if I walk away it's still complete. 

My apologies. 
Jami

**Comment by jami7** [comment]
Ok thank you. I sometimes don't really understand how the PR works so I'm learning as I go. Thought I needed to a PR after every set of changes so that if I walk away it's still complete. 

Sorry about that. 
Jami

Sent from Filmore, my iPhone

>

**Pull request closed without merging**
