### PR TITLE
Tags import + fix retrieving unfetched localized entries from database

### PR DESCRIPTION
**Pull request by erixtekila**
The filter was containing not the same text while localized.

I've added too tag support while importing.

### CODE REVIEW

**Comment by j0k3r** [comment]
Could you target the `dev` branch instead of the `master` ? Thanks.

**Comment by tcitworld** [comment]
Tags are already imported in dev branch, if I remember correctly.

**Comment by erixtekila** [comment]
Hm… how do I do that ? Should I checkout dev branch to commit in later ?

**Comment by erixtekila** [comment]
@tcitworld then just fix the unfetched entires sql query which doesn't work on localized version.

**Comment by j0k3r** [comment]
@erixtekila just re-create a PR and at the top, you will see the _target_ branch defined on the master, just change it to the dev branch

**Comment by tcitworld** [comment]
@erixteckila I will take care of it if you don't want to, no worries. ;-)

**Comment by erixtekila** [comment]
@tcitworld Did it ;)

**Pull request closed without merging**
