### PR TITLE
Cut entries title in card view: continued

### PR DESCRIPTION
**Pull request by modos189**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| Fixed tickets | #2055
| License       | MIT

The continuation of 
https://github.com/wallabag/wallabag/pull/2104

screen

### CODE REVIEW

**Comment by tcitworld** [comment]
That's quite a library for such a little feature. 🙁

**Comment by modos189** [comment]
Unfortunately, CSS is yet impossible

**Comment by modos189** [comment]
CSS can properly cut only one row.

Another option, you can use my previous code which adds the ellipsis.

**Comment by nicosomb** [comment]
> That's quite a library for such a little feature. 🙁

@tcitworld is right :( ... 

@wallabag/core @modos189 ellipsis or not?

**Comment by j0k3r** [comment]
Can't we just cut the title in the twig template, no matter if it finally use the full width?

**Comment by tcitworld** [comment]
With this that should be much better. Thanks a lot @modos189
Hope it will go without issues on nom/browserify on 2.1

**Comment by modos189** [comment]
While that did not added in npm. I did not have to work with him

**Comment by tcitworld** [comment]
It doesn't have to be added to npm online, the npm command can get resources from git.

**Comment by nicosomb** [comment]
@tcitworld can you do what is necessary for NPM please?

**Comment by tcitworld** [comment]
I will do it on 2.1 when this is merged.

**Comment by nicosomb** [comment]
OK, so we can merge this PR?

**Comment by tcitworld** [comment]
I didn't test it. But if it shows good, go ahead.

**Comment by nicosomb** [comment]
and what about #2104?

**Comment by modos189** [comment]
#2104 included to this PR

**Comment by nicosomb** [comment]
Tested 👍

**Comment by nicosomb** [comment]
👍

**Pull request merged**
