### PR TITLE
Added elCurator import

### PR DESCRIPTION
**Pull request by nicosomb**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | yes
| CHANGELOG.md  | no
| License       | MIT

https://www.elcurator.net will shutdown on december.

### CODE REVIEW

**Comment by janxbar** [comment]
In case you need some data to test the import, let me know. Unfortunately I cannot install Wallabag on my shared hosting, but I can provide you data from elCurator. I am considering to move my (large) link collection to Wallabag subscription site.

**Comment by j0k3r** [comment]
👍 for @janxbar. Could you provide us a small json file with tags in it? It'll help us update the PR.

poke @nicosomb

**Comment by janxbar** [comment]
This should work (export from 2018, I am waiting for current export). I have quite large set of bookmarks, the json from 2018 is 1.6MB.

[
  {
    "created_at": "2018-02-16 21:44:03 UTC",
    "title": "So what is a Windows “critical process” anyway? – The Old New Thing",
    "url": "https://blogs.msdn.microsoft.com/oldnewthing/20180216-00/?p=98035",
    "description": "",
    "tags": [
      "people raymond chen",
      "windows"
    ],
    "is_saved": true
  }
]

**Comment by nicosomb** [comment]
tags are already imported ;-)

**Comment by janxbar** [comment]
Thank you @nicosomb. Now the hard part - since elCurator is (almost) dead, there are users wanting to import elCurator data into app.wallabag.it, like myself. To help them, the import from elCurator should be available ASAP. After a while nobody will care.

**Comment by nicosomb** [comment]
I need review from @j0k3r ;-)

**Comment by j0k3r** [comment]
> tags are already imported ;-)

Are you sure?
I see nothing about tag in your `ElcuratorImport` class (in `prepareEntry`) nor in your json fixtures 🤔

**Comment by nicosomb** [comment]
I extend WallabagImport and it's the same way. I will update the test.

**Comment by j0k3r** [comment]
Good point!
Thanks for updating tests.

**Pull request merged**
