### PR TITLE
upgrade.rst (Creation of an upgrade page in the documentation)

### PR DESCRIPTION
**Pull request by biva**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | no
| Documentation | yes
| Translation   | no
| Fixed tickets | comma-separated list of tickets fixed by the PR, if any
| License       | MIT

Creation of an upgrade page in the documentation

### CODE REVIEW

**Comment by nicosomb** [comment]
@wallabag/core I wonder if this documetation shouldn't be there instead: http://doc.wallabag.org/en/master/user/installation.html

**Comment by biva** [comment]
I would use a different page, as in owncloud: https://doc.owncloud.org/server/9.1/admin_manual/installation/index.html and https://doc.owncloud.org/server/9.1/admin_manual/maintenance/upgrade.html

**Comment by nicosomb** [comment]
OK. Can you also update this file https://raw.githubusercontent.com/wallabag/wallabag/master/docs/en/index.rst to add your page in the menu please? 

I will create the french translation when your PR will be merged. (I think we need to work on the documentation about installation / update / migration ... It's quite confusing I think)

**Comment by biva** [comment]
Done here: https://github.com/wallabag/wallabag/pull/2012

**Comment by nicosomb** [comment]
You can work on the same branch, no need to open a pull request for each commit.

**Pull request merged**
