### PR TITLE
[WIP] 1st draft for new template

### PR DESCRIPTION
**Pull request by nicosomb**
Based on template found here http://www.blacktie.co/2014/07/dashgum-free-dashboard/

You can try this branch here: http://v2.wallabag.org/

### CODE REVIEW

**Comment by j0k3r** [comment]
I think we should try to find a solution to manage assets, like gulp, via node or bower maybe instead of pushing all these js and css file to the repo.

**Comment by tcitworld** [comment]
I think bower's the simplest system. Do we need more ?

**Comment by j0k3r** [comment]
Yep. We then need to list all assets dependencies.
Then a short `gulpfile.js` to uglify and concat them :)

**Comment by nicosomb** [comment]
Is that a problem for assets and bower / gulp if I use an existing template? 
I never used these tools.

**Comment by tcitworld** [comment]
No, it shouldn't be a problem, we just need to register everything the theme uses. With this system, it will be much easier to share dependencies (assets, js) between themes.

**Comment by nicosomb** [comment]
OK, I'll have a look. 
So Bower and Gulp.

**Comment by j0k3r** [comment]
:+1:

**Comment by nicosomb** [comment]
Moved to trash.

**Pull request closed without merging**
