### PR TITLE
Lock ocramius/proxy-manager

### PR DESCRIPTION
**Pull request by j0k3r**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| Fixed tickets | #1843
| License       | MIT

To avoid problem with PHP < 7.0

### CODE REVIEW

**Comment by bigretromike** [comment]
Any ETA for this fix ?

**Comment by j0k3r** [comment]
As soon as we are sure it fix the problem, we'll push a patch release.

**Comment by nicosomb** [comment]
Tests failed on PHP7. What can we do?

**Comment by j0k3r** [comment]
I want to test on Travis after clearing the cache but it's not possible at the moment. https://github.com/travis-ci/travis-ci/issues/5855

**Comment by j0k3r** [comment]
After clearing the cache, looks like tests are passing using proxy-manager 1.*

**Pull request merged**
