### PR TITLE
Feat/mass action UI

### PR DESCRIPTION
**Pull request by Simounet**
Hi there,
Some love for the mass action buttons layout.
You need to click on the second icon to toggle action buttons.

Actions enabled to the card view:
wallabag-card-view

On list view, before having clicked on the toggle button:
wallabag-list-view-mass-action-before-click

And after:
wallabag-list-view-mass-action-after-click

After toggling the actions, one click on the label will display the label input with a button to submit the form.

### CODE REVIEW

**Comment by j0k3r** [comment]
> And after:
> wallabag-list-view-mass-action-after-click

What is that missing translation? 🤔

**Comment by nicosomb** [comment]
It seems to be about "mass tagging", this feature is not yet developed. Maybe @Simounet want to develop it ? 😛

**Comment by Simounet** [comment]
@j0k3r I added this one to the `message.en.yml`. It's a placeholder to use as an example for the tagging feature.
@nicosomb It's already here or maybe did I miss something. 😚

**Comment by nicosomb** [comment]
@Simounet I think I missed something (or I forgot it).

**Comment by Simounet** [comment]
Do you need something more from me?

**Comment by Kdecherf** [comment]
> It seems to be about "mass tagging", this feature is not yet developed. Maybe @Simounet want to develop it ? stuck_out_tongue

Mass tagging has been added to `master`, it is not yet released though, see https://github.com/wallabag/wallabag/commit/08eb190c95ebaf8f8c63c0ca2589e00a99c15640

**Review by j0k3r — APPROVED** [review]

**Review by Kdecherf — APPROVED** [review]

**Pull request merged**
