### PR TITLE
Add doctrine clear after flush

### PR DESCRIPTION
**Pull request by nicosomb**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| Fixed tickets | N/A
| License       | MIT

After each `$em->flush()` while importing, we now ask to Doctrine to do a clear, thanks to @BitOne talk at Symfony Live about php memory leaks :+1: .

### CODE REVIEW

**Comment by j0k3r** [comment]
Well the sad part is that these two lines (the flush & clear) aren't tested because there is no test that import more than 20 entries (partially my fault).
Maybe, since we add more stuff in that `if`, it could be a good idea to cover these lines :grimacing:

**Comment by nicosomb** [comment]
Not so complicated to add a huge file for our tests, I can provide my wallabag v1 export.

**Comment by j0k3r** [comment]
We don't need hundred of entries, just at least 21 :)

**Comment by nicosomb** [comment]
I think I can provide 21 links :D

**Pull request closed without merging**
