### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by jrottenberg**
Docker support :
Run in sqlite mode by default
Support for mysql, at run time mount your config if you have one

See https://github.com/wallabag/wallabag/pull/1115 for full history.

Test with :
    
       docker build -t wallabag .
       docker run -it -p 8080:80 wallabag
       open http://docker_host:8080

### CODE REVIEW

**Comment by nicosomb** [comment]
ping @bobmaerten

**Comment by bobmaerten** [comment]
I have to admit I run wallabag on docker for my needs, and sqlite as a single user is quite enough.
There is [docker-wallabag](https://github.com/bobmaerten/docker-wallabag) running 1.9 and a new image should be made for 2.x. Docker has changed since then, docker-compose is the new way to go, and I think that should be included directly in wallabag like so many other oss-projects nowadays (discourse, gitlab, etc.)

**Comment by jrottenberg** [comment]
Good point @bobmaerten , I've added docker-compose integration.

Not sure what standard you'd go with, but basically you define a mysql dbname/user and pass in the docker-compose file, and enter those values on the installer : 

<a href="http://imgur.com/51qdbOU"></a>


Of course you can stick to standalone + sqlite solution as well.

**Comment by nicosomb** [comment]
@bobmaerten @jrottenberg do you think this PR is good to be merge?

**Comment by bobmaerten** [comment]
Don't really know about the php/sql part, but a basic Dockerfile/docker-compose.yml is better than nothing. Maybe add something about credentials in a .md file, as I regulary have question about it on my docker-wallabag repo.

**Comment by jrottenberg** [comment]
Oh did I miss something ? I can add a comment on a new markdown file if you need regarding credentials, as of now it was using simple value defined in docker-compose not too sure if we even needed that (could have use root + no password as well)

**Comment by nicosomb** [comment]
You missed nothing, it's just because we won't work on 1.9.x anymore. You can help us to create a Dockerfile for wallabag v2 :-)

**Comment by jrottenberg** [comment]
Deal !

**Pull request closed without merging**
