### PR TITLE
Improved tags list

### LINKED ISSUE #3804: Make the untagged list more visible
Would be a nice feature to filter pages without tags.
Thanks

### PR DESCRIPTION
**Pull request by nicosomb**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| CHANGELOG.md  | no
| License       | MIT

Fixed #3804, #4135 

Screenshots: 

Capture d’écran 2019-10-01 à 15 27 39

Still one issue (for large text): 
Capture d’écran 2019-10-01 à 15 46 35

Before: 
Capture d’écran 2019-10-01 à 15 49 28

### CODE REVIEW

**Comment by nicosomb** [comment]
Before 

Capture d’écran 2020-04-12 à 17 05 26

After 

Capture d’écran 2020-04-12 à 17 04 17

**Comment by Kdecherf** [comment]
(Don't forget to rebase and update the compiled assets before merging)

**Comment by tcitworld** [comment]
Why the empty space between the number of articles for a tag and the action icons ? The text should use all the space available.

**Comment by nicosomb** [comment]
Because I truncate via a twig tag the tag. Do you think we need to do with an other way?

**Comment by j0k3r** [comment]
I think he's talking about a CSS way maybe?

**Comment by tcitworld** [comment]
Yup, good old CSS ellipsis.

**Comment by nicosomb** [comment]
@tcitworld could you help me please for this point please?

**Comment by Simounet** [comment]
I did some correction to your code @nicosomb . I used a `grid` layout with a minimum width of `200px`. With long tags, we are loosing the count but we can see it through a mouseover and there is a lot of space on mobile.
Here are the screenshots:
mobile
tablet
laptop
desktop

I'm waiting for the push rights to this branch to share my code.

**Comment by Simounet** [comment]
And what about a tag instead of a sentence without a visual indicator that this is a link for the "See all untagged entries"? I think I can copy the `entry.page_titles.untagged` translation.
Capture d’écran 2020-04-19 à 18 42 59

**Comment by nicosomb** [comment]
Looks good for me

**Comment by Simounet** [comment]
I pushed theses changes in the latest fixup.

**Comment by Simounet** [comment]
Done.

**Comment by j0k3r** [comment]
@Simounet It was already squashed by @nicosomb anyway :)

**Comment by Simounet** [comment]
Sorry. :)

**Pull request merged**
