### PR TITLE
Corrected french translation

### PR DESCRIPTION
**Pull request by Jibec**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | ?
| Deprecations? | no
| Tests pass?   | ?
| Documentation | no
| Translation   | yes
| Fixed tickets | 
| License       | MIT

Hi, I corrected many little typo problems and tiny translation issues. To make quote/apostrophe clean-up, I standardized the YAML quote.
As we are not yet in version 2.2, i decided to use branch 2.0... I had no idea wich files to edit, I hope I did all french files.

### CODE REVIEW

**Comment by j0k3r** [comment]
Thanks for that but you should rather target the master branch which is the current version and will also be included in the upcoming 2.2.

**Comment by Jibec** [comment]
do you know how to merge it with master branch? I'm afraid I do not have the skills to do it and would prefer not to have to redo the work ;)

**Comment by j0k3r** [comment]
Changing branch is easy but you'll have to update your work because the 2.0 branch was quite old comparing to the master. And as you can see, your work generate conflict.
Can you fix conflicts?

**Comment by Jibec** [comment]
"Only those with write access to this repository can merge pull requests."
No problems, I'll redo the work on Master. Next time I'll read contributor guide prior to submit pull request ;)

**Comment by j0k3r** [comment]
➡️ https://github.com/wallabag/wallabag/pull/2519

**Pull request closed without merging**
