### PR TITLE
Feat/domain status filters html types

### PR DESCRIPTION
**Pull request by Simounet**
Changed the types and accepted values for status and domain filters (right column). Better for mobile inputs.

### CODE REVIEW

**Comment by nicosomb** [comment]
@Simounet could you please fix your PR with php cs ?

**Comment by j0k3r** [comment]
Shouldn't we target 2.6.5 for that?

**Comment by Simounet** [comment]
I'll change the branch and push again.

**Comment by Simounet** [comment]
Working with everything but PHP7.4. Any clues?

**Comment by j0k3r** [comment]
Maybe be cause of https://github.com/wallabag/wallabag/blob/49eea9f92173876213c5cedab1a9df5cdc6c42a9/tests/Wallabag/CoreBundle/Controller/EntryControllerTest.php#L1390

**Comment by Simounet** [comment]
It fails before that test and only with 7.4. 😢

**Comment by j0k3r** [comment]
I've tested locally on PHP 7.4 and got: 
image

**Comment by Simounet** [comment]
Working when value cast as integer.

**Comment by nicosomb** [comment]
PHP 8.x is more restrictive for that.

**Comment by Simounet** [comment]
Yep, I was expecting the opposite. Working on 7.x and not working on 8+. Glad to see it working anyway.

**Review by j0k3r — APPROVED** [review]

**Pull request merged**
