### PR TITLE
Added help on config screen

### LINKED ISSUE #2575: On "changing password" screen, display the requirements
When we are on the screen to change the password, it will be more user friendly to display the requirements before we submit the form. I think about this message 

> Password should by at least 8 chars long

### PR DESCRIPTION
**Pull request by nicosomb**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | yes
| Translation   | yes
| Fixed tickets | #2576, #2575
| License       | MIT

Fix #2575, #2576 

I prefered tooltips instead of link to the documentation, see below.

capture d ecran 2016-11-12 a 13 20 52

Todo:

- [x] question mark icon on baggy theme

### CODE REVIEW

**Comment by nicosomb** [comment]
WIth baggy theme, I just added icons with title on it. If we want to improve it after, it's possible.

**Comment by tcitworld** [comment]
Screenshots ! \o/

**Comment by nicosomb** [comment]
capture d ecran 2016-11-16 a 22 36 43

**Comment by nicosomb** [comment]
for material, see the first post.

**Comment by j0k3r** [comment]
Rebased needed.

**Pull request merged**
