### PR TITLE
Make dark scroll bar in Chromium-based browsers

### PR DESCRIPTION
**Pull request by rakleed**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| CHANGELOG.md  | no
| License       | MIT

Make a dark scrollbar in Chromium based browsers in a dark theme.

### CODE REVIEW

**Comment by rakleed** [comment]
@Kdecherf @nicosomb @tcitworld please take a look.

**Comment by nicosomb** [comment]
Hello! Is that possible to have a screenshot before / after ?

**Comment by rakleed** [comment]
@nicosomb

<details>
<summary>Main screen</summary>
Before:

2021-09-17 15-45-02 Unread entries – wallabag - Google Chrome

After:

2021-09-17 15-45-54 Unread entries – wallabag - Google Chrome

</details>

<details>
<summary>Article screen</summary>
Before:

2021-09-17 15-46-42 Here's everything Apple didn't announce at its iPhone 13 event (9to5mac com) – wallabag - Google Chrome

After:

2021-09-17 15-47-18 Here's everything Apple didn't announce at its iPhone 13 event (9to5mac com) – wallabag - Google Chrome

</details>

**Review by nicosomb — APPROVED** [review]

**Comment by rakleed** [comment]
@Kdecherf (if you have macOS, on other OS I think something similar needs to be done) to reproduce the problem in the macOS system preferences › General for "Show scroll bars:" must be set to "Always" (it also works for me with "Automatically based on mouse or trackpad", which is the default option). And you apparently have "When scrolling" selected.

**Comment by rakleed** [comment]
@j0k3r could you please take a look?

**Comment by j0k3r** [comment]
I do not have Chrome installed but I'm using Brave and the scroll bar doesn't change.
I've enabled macOS to always display scroll bar.

> Version 1.37.111 Chromium: 100.0.4896.79 (Build officiel) (x86_64)

image

**Pull request closed without merging**
