### PR TITLE
Fix UTF-8 encoding before JSON export

### PR DESCRIPTION
**Pull request by ymage**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes|no
| Documentation | no
| Translation   | no
| Fixed tickets | #1747 
| License       | MIT

### CODE REVIEW

**Comment by benediktg** [comment]
I have tried this patch (see commands down below) but umlauts got messed up after the articles were imported into Wallabag v2.

```
cd /path/to/wallabag
wget https://github.com/ymage/wallabag/commit/206c2a734e2a0d100af6d772d90b01c5cb8fe870.patch
patch -blp1 < 206c2a734e2a0d100af6d772d90b01c5cb8fe870.patch
```

**Comment by tcitworld** [comment]
> umlauts got messed up after the articles were imported into Wallabag v2.

And the import worked before with these umlauts ?

**Comment by ymage** [comment]
Maybe, I should add a JSON_UNESCAPED_UNICODE during json_encode to avoid this mess

**Comment by benediktg** [comment]
@tcitworld Yes, without or after undoing this patch and trying the export-import-procedure umlauts are not messed up. With only few articles there are no problems at all. I get the empty file because of the hundreds of articles as I have assumed in #1747.

**Comment by ymage** [comment]
@benediktg Can you provide us some test samples in order to improve this patch ?

**Comment by benediktg** [comment]
@ymage The slightly older file is with this patch applied and exported, the other file is after I have undone the patch and exported again.

[wallabag-exports.zip](https://github.com/wallabag/wallabag/files/206927/wallabag-exports.zip)

**Comment by tcitworld** [comment]
Thanks @ymage, this seems to work. I'm just trying to see what happens with huge amount of data.

**Comment by benediktg** [comment]
I tried the patch again with
```
wget https://patch-diff.githubusercontent.com/raw/wallabag/wallabag/pull/1866.patch
patch -bp1 < 1866.patch
```
Here is the resulting exported JSON (I just added .txt to the filename because Github requires it):
[wallabag-export-2-2016-04-10.json.txt](https://github.com/wallabag/wallabag/files/211857/wallabag-export-2-2016-04-10.json.txt)

And when I import that to Wallabag v2 it looks good, too. Now I just have to see how it behaves with big amounts of articles.

**Comment by nicosomb** [comment]
Can we merge?

**Comment by benediktg** [comment]
On the other hand the patch did not create new problems, so there is nothing wrong with merging it in my opinion.

**Comment by ymage** [comment]
Well,

This patch deals only with UTF-8 encoding issue before json_encode. 
It does not cover other export issues.

**Pull request merged**
