### PR TITLE
Extendemailshare

### PR DESCRIPTION
**Pull request by tcitworld**
Wait until icomoon is done, i mixed up a bit here.

### CODE REVIEW

**Comment by nicosomb** [comment]
You created your branch from mine, right? There are my commits inside. 

This PR is to add an excerpt into the mail?

**Comment by tcitworld** [comment]
Right, that's why we better wait until the other one is merged.

Yup, that's right. Do you want to make this an option ? It works on all mail clients I've tested (Thunderbird, Gmail, Geary)

**Comment by nicosomb** [comment]
Nice feature :-)

I don't understand why we need the other PR, btw.

**Comment by tcitworld** [comment]
Because I made too much merge mistakes and I'm afraid of making more. So I want to take my time. :D

**Comment by nicosomb** [comment]
OK.

**Pull request closed without merging**
