### PR TITLE
Tag supports + import unfetched localized entries

### PR DESCRIPTION
**Pull request by erixtekila**
The filter was containing not the same text while localized. 
I've also added tag support while importing.

### CODE REVIEW

**Comment by erixtekila** [comment]
Ah yes, I did it ;)

**Comment by j0k3r** [comment]
Could you then rebase your branch against the dev one? And you'll be ok :)

**Comment by erixtekila** [comment]
Do you need that :

1. I rebase to dev
2. I republish the PR

or is it OK now ?

**Comment by j0k3r** [comment]
Once you've rebase your branch, you should `push -f` it to update the PR

**Pull request closed without merging**
