### PR TITLE
Italian documentation added

### PR DESCRIPTION
**Pull request by matteocoder**
There are some missing links in various articles. Please let me know how I can fix this :)

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | no
| Documentation | yes
| Translation   | yes
| Fixed tickets | #...
| License       | MIT

### CODE REVIEW

**Comment by matteocoder** [comment]
Great! However, there are some parts in the original documentation that link to other articles inside the documentation itself, so I imagine that I can fix that once the documentation is uploaded to the wallabag website.

**Comment by nicosomb** [comment]
Yes, we'll fix that when your PR will be merged. 

FYI, I also planned to change our documentation tool. But I need time.

**Comment by nicosomb** [comment]
Thank you 👍

**Comment by nicosomb** [comment]
http://doc.wallabag.org/it/latest/ 🎉

**Pull request merged**
