### PR TITLE
Mass action layout improved

### LINKED ISSUE #6818: Mass actions: autofocus on tags textfield when clicking on add tags button
A recent update changed the way check-boxes and buttons work for mass actions, including the text field for adding/removing tags. Now we must click on the "add tags" button first to show the field.

However there's no auto focus, which forces the user to do an extra click to focus on the field and start editing tags.

Considering that when we click on the "add tags" button we are expected to add or remove tags, I think that we could directly enable focus on this field.

2023-08-08-144253_4480x2520
2023-08-08-144805_4480x2520

### PR DESCRIPTION
**Pull request by Simounet**
Some improvements for the main top parts of the homepage. More mobile friendly and less clicks for adding tags. Should fix #6818 by removing the click on the tag before being able to submit the form. I'm not sure if it's better with the icon before or after the input. Visually better with the icon before but I think the user flow is better with the icon after.

A. wallabag-icon-before
B. wallabag-icon-after

Before

wallabag-desktop-before

wallabag-mobile-before

After

wallabag-desktop-after

wallabag-mobile-after

### CODE REVIEW

**Review by j0k3r — DISMISSED** [review]
As there is a title on the label (the one after the input), it seems ok to me!

**Comment by Simounet** [comment]
I'm sorry but I lost your approval after updating the code for using the color variable.
Do you prefer the A or B version?

**Comment by j0k3r** [comment]
A :)

**Review by j0k3r — APPROVED** [review]

**Review by nicosomb — DISMISSED** [review]
`A`

**Comment by Simounet** [comment]
I changed the code for the A version. You have to approve it again @j0k3r @nicosomb , sorry about that.

**Review by nicosomb — APPROVED** [review]

**Review by j0k3r — APPROVED** [review]

**Pull request merged**
