### PR TITLE
Enhanced navigation menu in material theme

### PR DESCRIPTION
**Pull request by nicosomb**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | yes
| CHANGELOG.md  | no
| License       | MIT

I created a "my account" menu. 

Before: 

Capture d’écran 2020-04-21 à 08 02 12

After: 

Capture d’écran 2020-04-23 à 13 51 57

Sidebar : 

Capture d’écran 2020-04-23 à 13 52 03

### CODE REVIEW

**Comment by Simounet** [comment]
I think you should switch random and filter. To me, filtering is far more important than picking a random entry.

**Comment by nicosomb** [comment]
You mean: random articles should be on the sidebar?

**Comment by Simounet** [comment]
Yep. Invert the random and filter buttons.

**Comment by Kdecherf** [comment]
Given that 'Filter entries' and 'Export' open a sort-of dropdown I would let them in the top navbar as before.

@Simounet I second that, the 'Random' button could go on the left menu.

**Comment by nicosomb** [comment]
About the random link, the label is too long for the sidebar. What do you suggest?

**Comment by nicosomb** [comment]
I pushed some changes and updated screenshots.

**Comment by nicosomb** [comment]
I think that the Random item should stay in the top navbar.

**Comment by nicosomb** [comment]
Squashed. Need one more approval.

**Comment by Simounet** [comment]
> 
> 
> I think that the Random item should stay in the top navbar.

Do you have any usage statistics from wallabag.it to be sure it's an important feature to have at this location?

**Comment by nicosomb** [comment]
No, I don’t have this kind of analytics

**Pull request merged**
