### PR TITLE
fix #1457 & update materialize

### LINKED ISSUE #1457: Use Chips for tags in material theme
see http://materializecss.com/chips.html

### PR DESCRIPTION
**Pull request by tcitworld**
tags_chips

### CODE REVIEW

**Comment by nicosomb** [comment]
:+1:

**Comment by tcitworld** [comment]
Are grey tags on grey background sufficiently visible ?

**Comment by j0k3r** [comment]
Why don't you let them blue like there were before?

image

**Comment by nicosomb** [comment]
Done. I also removed the close icon. We'll add it when we'all the remove tag feature.

**Pull request merged**
