### PR TITLE
better display for filters on baggy (without popup)

### PR DESCRIPTION
**Pull request by tcitworld**
It's just a preview of what I had in mind, not perfect work.

### CODE REVIEW

**Comment by nicosomb** [comment]
screenshot please? :-)

**Comment by j0k3r** [comment]
Yes screenshot please?
I also need to rebase `v2-baggy-themes` :)

**Comment by tcitworld** [comment]
Desktop : 
filter_desktop
Mobile :
filter_mobile

**Comment by j0k3r** [comment]
From my POV, it takes too much space like that.

**Comment by tcitworld** [comment]
Yeah, I admit but it something's still bothers me with the popup, can't really tell what. I'll try to put the same thing as for material theme, a panel on the right side.

**Comment by j0k3r** [comment]
Could be a good idea.
Just to let you know, I'll rebase my branch and fix tests. Then you could do you work directly on my branch instead of this one.

**Comment by tcitworld** [comment]
How's something like this ?
filter-desktop-sidepanel

I need to bring css animations.

**Comment by j0k3r** [comment]
Should we close this one in favor to #1404 ?

**Comment by tcitworld** [comment]
Yup.

**Pull request closed without merging**
