### PR TITLE
remove docker stuff, it moved to other repo

### PR DESCRIPTION
**Pull request by Strubbl**
The docker stuff hasn't been updated since a while. All docker stuff is
now maintained in the repository https://github.com/wallabag/docker

| Q             | A
| ------------- | ---
| Bug fix?      | /no
| New feature?  | /no
| BC breaks?    | /no
| Deprecations? | yes/
| Tests pass?   | 
| Documentation | /no
| Translation   | /no
| Fixed tickets | #...
| License       | MIT

### CODE REVIEW

**Comment by j0k3r** [comment]
And we'll close https://github.com/wallabag/wallabag/pull/2966 then

**Comment by aaa2000** [comment]
Is it the same goal ? One is for production, the other is for development and makes the installation easier for the contributors

**Comment by Strubbl** [comment]
@aaa2000 is this one for development? i did not know that. does anybody use it?

**Comment by tcitworld** [comment]
I don't think anyone still uses it. :/

**Comment by aaa2000** [comment]
I use it, I follow the documentation https://doc.wallabag.org/en/developer/docker.html with some modifications

**Comment by Strubbl** [comment]
Okay, since it is still used, i am closing this PR

**Pull request closed without merging**
