### PR TITLE
Fix fetched entries when localized

### PR DESCRIPTION
**Pull request by erixtekila**
The stored message in DB used a not localized text.

### CODE REVIEW

**Comment by tcitworld** [comment]
The use of `$url->isCorrect()` is a great idea. I wonder why we haven't used before.
Thanks for that.

**Comment by erixtekila** [comment]
Thanks. While inserting bookmarks from firefox for example, there could be some "about:something" URL which mess the whole import process. 
Anyhow, you'd also add a mean to bypass certain unfetchable articles that may block the whole process.

**Comment by tcitworld** [comment]
You manage to import bookmarks from Firefox as JSON, you mean, right ?
I thought unfetchable article were ignored, I'll have to check that again.

WIll test you PR today.

**Comment by erixtekila** [comment]
@tcitworld Either json or html.

**Comment by tcitworld** [comment]
>  Will try on 2 if I get some time ?!

v2 is quite WIP, I don't think import has been implemented yet

**Pull request merged**
