### PR TITLE
Fix form user display when 2FA is disabled

### PR DESCRIPTION
**Pull request by nicosomb**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| Fixed tickets | N/A
| License       | MIT

When Two factor authentication is disabled, the `form_rest` displayed the label of the 2FA field, see below 

capture d ecran 2016-05-18 a 14 59 32

### CODE REVIEW

**Comment by tcitworld** [comment]
Ready ?

**Comment by j0k3r** [comment]
2FA isn't displayed in baggy?

**Comment by tcitworld** [comment]
I see it.

2factorauth

**Comment by nicosomb** [comment]
I just fixed the form for baggy theme too. RFR.

**Comment by j0k3r** [comment]
Tests are fixed now.

- `tearDownAfterClass` now ensure tests after the InstallCommand test will have a clean database.
Previous attempt failed because of a foreign key
- Also, nightly on Travis seems to target PHP 7.2-dev, so I put 7.1 in requirement and moved nightly in allowed failures.
- And it seems xdebug isn't shipped with PHP 7.1, so I added a workaround to avoid build to fail when trying to remove xdebug.ini file.

**Comment by nicosomb** [comment]
👍

**Comment by j0k3r** [comment]
:+1:

**Pull request merged**
