### PR TITLE
Share to Shaarli - Include tags

### PR DESCRIPTION
**Pull request by lapineige**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | 
| Documentation | no
| Translation   | no
| Fixed tickets | #2664 
| License       | MIT

Sharing to Shaarli did not include article's tags. This PR add this feature to baggy and material themes.

NB: this is supported only with a quite recent version of Shaarli (it doesn't work with the [original version](https://github.com/sebsauvage/Shaarli), only with the community fork)

### CODE REVIEW

**Comment by lapineige** [comment]
I see that one of the tests failed - but I don't understand what's wrong.
Can someone explain it to me, in order to fix it ? Thanks :)

**Comment by tcitworld** [comment]
Postgresql often fails. I've relaunched the task.

**Comment by lapineige** [comment]
I added `url_encode` but I'm not sure it's needed - Shaarli deals without any problem with some accents in the url, but I guess it's more secure to have the encoding ?

**Comment by lapineige** [comment]
I'm really happy that this feature is now part of wallabag 2.2, and to be honest, and a bit proud when seeing my little contribution in the release notes: https://wallabag.org/en/news/new-release-wallabag-2-2-finally

But I've to to give credit where credit is due, I couldn't do anything without your help @nicosomb and @j0k3r :)
Thanks again for your hard work on wallabag !

**Pull request merged**
