### PR TITLE
V2 docker support

### PR DESCRIPTION
**Pull request by DmitrySandalov**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | yes
| Translation   | no
| Fixed tickets | #1858 
| License       | MIT

### CODE REVIEW

**Comment by nicosomb** [comment]
ping @FabienM

**Comment by FabienM** [comment]
@nicosomb what is your plan for this `docker-compose` ?
When i originally contributed it, the plan was only to provide a quick development environment, so developers continue to manage their own composer workflows and wallabag install workflow.

I think this PR fix another goal, to provide a end-user docker setup that is able to start a "production" instance of Wallabag. For such a case, i would rather use a "all-in-one" docker image instead of relying on docker-compose plumbering.

But you have to decide what files have their places in the main source repo, and what file would be better maintained in a new git repo (`wallabag/docker`).
Personnaly, i would keep the main repo developer-oriented and i would create a all-in-one docker file in an other repo, but maybe @DmitrySandalov have some contrary arguments :-)

**Comment by nicosomb** [comment]
I just created a new repo for production environment: https://github.com/wallabag/docker
We'll keep our `docker-composer.yml` in wallabag/wallabag for developers. 

When production docker-compose file will exist, we'll update documentation to explain what are the differences between those files.

**Comment by nicosomb** [comment]
@DmitrySandalov I added you in the wallabag/docker team. 

I close this PR and feel free to push your file in https://github.com/wallabag/docker

**Pull request closed without merging**
