### PR TITLE
Update messages.pl.yml

### PR DESCRIPTION
**Pull request by mruminski**
| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | yes/no
| Deprecations? | yes/no
| Tests pass?   | yes/no
| Documentation | yes/no
| Translation   | yes/no
| Fixed tickets | #...
| License       | MIT

translate action_mark_as_read section to polish

### CODE REVIEW

**Comment by nicosomb** [comment]
Thank you @mruminski!

**Comment by tcitworld** [comment]
Regular tests failing for some reason.

**Comment by nicosomb** [comment]
This test failed on an other PR few days ago.

**Comment by j0k3r** [comment]
The translation build is 💚 
Thanks @mruminski always up to date ! 🚀

**Pull request merged**
