### PR TITLE
Changed translation for All entries

### PR DESCRIPTION
**Pull request by nicosomb**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | no
| Documentation | no
| Translation   | yes
| Fixed tickets | #3019 
| License       | MIT

I don't know how to fix the  `Also, export panel has the ?tag= parameter.` issue. 

@wallabag/translators I need your help.

### CODE REVIEW

**Comment by tcitworld** [comment]
> I don't know how to fix the Also, export panel has the ?tag= parameter. issue.

?

**Comment by nicosomb** [comment]
In your issue (#3019), you talked about that.

**Comment by matteocoder** [comment]
In italian, the line "All entries" is "Tutti gli articoli",

**Comment by mruminski** [comment]
For Polish: "All entries" -> "Wszystkie wpisy"

**Comment by j0k3r** [comment]
So, when you filter your entries the title will still be "all entries"? 🤔

**Comment by mruminski** [comment]
@j0k3r I think in this case title should be "Filtered entries" or something like that

**Pull request closed without merging**
