### PR TITLE
Added creation date on entries view

### LINKED ISSUE #2477: Add the creation date on the card
It would be nice to see the creation date somewhere on the card on the main page, maybe when clicking on the 3 dots icon (there is more space).

### PR DESCRIPTION
**Pull request by nicosomb**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | /n
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| Fixed tickets | #2477
| License       | MIT

Fix #2477 

## Baggy

capture d ecran 2016-11-10 a 19 19 49

## Material 

capture d ecran 2016-11-10 a 19 22 49

### CODE REVIEW

**Comment by tcitworld** [comment]
Not really liking how the screenshots look like. :/

**Comment by nicosomb** [comment]
About material? Or both?

**Comment by nicosomb** [comment]
And what about 

capture d ecran 2016-11-11 a 20 36 53

?

**Comment by j0k3r** [comment]
How is this rendered when screen are smaller?

**Comment by nicosomb** [comment]
capture d ecran 2016-11-14 a 10 00 09

Need to fix it.

**Comment by tcitworld** [comment]
It can be hidden on small devices. Also, please rebase.

**Comment by nicosomb** [comment]
Hidden on small devices 👍

**Pull request merged**
