### PR TITLE
Cleanup baggy

### PR DESCRIPTION
**Pull request by j0k3r**
- Move baggy in theme folder
- Cleanup _global_ theme
- Make filter more beautiful

image

And lower domain search length because when searching for "bbc" I got no result .. sigh.

### CODE REVIEW

**Comment by nicosomb** [comment]
Can you rebase your PR please?

**Comment by j0k3r** [comment]
Yeah, I also need to fix tests.

**Comment by tcitworld** [comment]
I was thinking more like a horizontal display for the filters with baggy theme, above the entries, in one line.
I'll try to merge that with some of my work.

**Comment by j0k3r** [comment]
You mean, filters will be always displayed?

**Comment by tcitworld** [comment]
No, also with a button to show them, but next to the other, not in a popup.

**Comment by tcitworld** [comment]
I created  #1402 for you to have a look.

**Comment by nicosomb** [comment]
Hi again @tcitworld! Do you still have work on this PR?

**Comment by tcitworld** [comment]
#1404 must be merged here first.

**Comment by tcitworld** [comment]
Also, maybe other features to bring for this theme.

**Comment by j0k3r** [comment]
It could be cool if we can merge that asap to avoid conflict and more work to be done. Since I moved some files if we had things to baggy, I'll need to update this PR quite often.

**Comment by nicosomb** [comment]
If we fix the current conflicts, do you think we can merge?

**Comment by j0k3r** [comment]
We still need to merge #1404 first

**Comment by tcitworld** [comment]
Merge it, I'll enhance it when I'll get a working internet connexion.

**Comment by nicosomb** [comment]
#1404 is merged and this one is mergeable. Let's go?

**Comment by j0k3r** [comment]
Good to merge :white_check_mark:

**Pull request merged**
