### PR TITLE
Importtags

### PR DESCRIPTION
**Pull request by tcitworld**

### CODE REVIEW

**Comment by tcitworld** [comment]
Can now import tags from Pocket.

**Comment by nicosomb** [comment]
OK, you open a PR and merge it ;-) Where is the code review ? :-P

**Comment by nicosomb** [comment]
Oh it's a PR from @kaffeeringe, right?

**Comment by tcitworld** [comment]
That's right. And since his PR went to master, I wanted to be sure there wouldn't be any problems, so I reviewed this first.

**Comment by nicosomb** [comment]
:+1:

**Pull request merged**
