### PR TITLE
Added tags on list view

### PR DESCRIPTION
**Pull request by nicosomb**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| Fixed tickets | #2808, #2867 
| License       | MIT

capture d ecran 2017-05-29 a 15 21 31

### CODE REVIEW

**Comment by tcitworld** [comment]
Will do tonight.

**Comment by tcitworld** [comment]
Seems I forgot.

**Comment by nicosomb** [comment]
Comment on twitter: 

> Perhaps with a differentiation between title and urls colors and less padding around tags.

**Comment by nicosomb** [comment]
Last version 

capture d ecran 2017-05-29 a 15 21 31

**Comment by nicosomb** [comment]
I reduced it, it was worst before. 

On this PR, I need help from @tcitworld to fix mobile view (he will fix it after his nap 💤 )

**Comment by Rurik19** [comment]
How it looks if there are many tags, when they don't fit in one line?

**Comment by tcitworld** [comment]
> How it looks if there are many tags, when they don't fit in one line?

It's limited to 3 tags.

**Comment by Rurik19** [comment]
>It's limited to 3 tags.
But article can have more tags? Should to have "... x more" pseudo-tag with popup of some sort with other tags?

**Comment by nicosomb** [comment]
> But article can have more tags? Should to have "... x more" pseudo-tag with popup of some sort with other tags? 

Sure. But in an other PR 😋

**Comment by j0k3r** [comment]
Are we good to go then?

**Comment by nicosomb** [comment]
Nope. Still waiting the end of @tcitworld's nap.

**Comment by nicosomb** [comment]
I moved the domain name


With this fix, mobile view is better. Not perfect, but better. 
We can merge.

**Comment by tcitworld** [comment]
There seem to have issues...
selection_077

**Comment by j0k3r** [comment]
Only when images aren't displayed?

**Comment by tcitworld** [comment]
Nope. Pictures are always outputted as `` for some reason.

**Comment by tcitworld** [comment]
selection_078

**Comment by nicosomb** [comment]
Oh Did I forget a check on preview field? 😥

**Comment by tcitworld** [comment]
selection_081

**Comment by nicosomb** [comment]
Still broken

capture d ecran 2017-05-31 a 15 21 30
capture d ecran 2017-05-31 a 15 23 26

**Comment by tcitworld** [comment]
> Still broken

If you're in dev environment, you need to do `yarn run build:dev`.

**Comment by tcitworld** [comment]
They're still a little too big, I'll try improving that.

**Pull request merged**
