### PR TITLE
Show untagged entries count on tag list

### LINKED ISSUE #3235: Show article counter in untagged articles
Show article counter in untagged articles
2017-06-16 23_32_17-etiquetas wallabag

### PR DESCRIPTION
**Pull request by j0k3r**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| License       | MIT

Fix #3235

image

### CODE REVIEW

**Comment by tcitworld** [comment]
We might as well hide this line if there's no untagged articles ?

**Comment by j0k3r** [comment]
> We might as well hide this line if there's no untagged articles ?

It might be troubling and I think with that addition (the counter), we don't need to remove the link, it's more obvious that we won't have entry if you click on it:
image

**Comment by tcitworld** [comment]
> > We might as well hide this line if there's no untagged articles ?
> 
> It might be troubling and I think with that addition (the counter), we don't need to remove the link, it's more obvious that we won't have entry if you click on it:
> image

I would still like to rephrase to something like: « No untagged entries » and remove an useless link.

**Comment by j0k3r** [comment]
Updated:
image

**Pull request merged**
