### PR TITLE
Add config option to set a base URL

### LINKED ISSUE #1075: Using Wallabag with Apache in a location different than /
Hi,

I'm trying to setup Wallabag as an additional location on my domain with an "domain.tld/wallabag/ location. I've configured the Apache2 server to make a ProxyPass for the mentioned location to the server with the Wallabag instance. 

Problem: Wallabag seems to rewrite the URL to the root (/) location which leads to a redirect to my main webpage. 

Is there any way to prevent this rewrite of the URL? Does Wallabag support a different location as root (/) ?

### PR DESCRIPTION
**Pull request by MoriTanosuke**
This PR fixes #1075.

When running behind a reverse proxy it is useful to generate links using the public internet address. To set the base URL you have to add the following line to your `inc/config.inc.default.php`:

    @define ('BASE_URL', 'https://yourhostname/sub/directory/wallabag/');

Themes will now generate links to CSS and JS using the *BASE_URL* value, like

    <script src="https://yourhostname/sub/directory/wallabag/themes/_global/js/jquery-2.0.3.min.js"></script>

### CODE REVIEW

**Comment by tcitworld** [comment]
Made a little modifications, see #1226.

**Comment by fionnb** [comment]
Hello,

could it be that this functionality did not make it into v2? There was even a bounty paid for this :-)
At least I could not find a sensible way to enable it for your v2 docker container!
If this is missing again, I would suggest to reopen the issue.

**Comment by MoriTanosuke** [comment]
I'm also struggling with a setup using v2 and an apache reverse proxy setup. I'm using the docker installation and I use an apache2 container with a `Location` directive doing a `ProxyPass` and `ProxyPassReverse` to the wallabag container. But when I open https://myapachecontainer/wallabag/ I get to the login form with all images, CSS and JS again pointing to */bundles/...*

Example:

    <link rel="apple-touch-icon" type="image/png" href="/bundles/wallabagcore/themes/_global/img/appicon/apple-touch-icon-152.png" sizes="152x152">

Is there anything else I have to do?

**Comment by j0k3r** [comment]
@fionnb v2 code is completely different from the v1. That's why the code didn't make it to the v2.
If you guys still have this issue please open a new one with a step by step to reproduce (and information etc.) and reference this issue in the new one.

**Pull request closed without merging**
