### PR TITLE
Fix filter reading time

### LINKED ISSUE #1975: Wrong reading time in filter entries
### Issue details

I set the reading speed as 100 words per minute in the Config.
In the filter entries, it uses the default reading time of 200 words per minute, so if I filter between 1 and 5 minutes, I see elements with reading times from 2 to 10 minutes.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.3
* Installation via git clone
* php version: 5.6.19-0+deb8u1
* OS: Debian 8.4
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): PostgreSQL

### Steps to reproduce/test case

Go to filter entries, put from 1 to 5 in the "Reading time in minutes" parameter and click the "Filter" button. The result is entries with more than 5 minutes in reading time.

### PR DESCRIPTION
**Pull request by nicosomb**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| Fixed tickets | #1975 
| License       | MIT

Fix #1975 

I'm sure that @j0k3r will tell me "tests are missing"... :smile:

### CODE REVIEW

**Comment by tcitworld** [comment]
Well, they could have been useful in that case. :-)

**Comment by j0k3r** [comment]
I agree with @tcitworld :)

**Comment by nicosomb** [comment]
What kind of tests?

**Comment by j0k3r** [comment]
I would say, write a test that fails without your change and that fail pass with your change :)

**Comment by nicosomb** [comment]
I can't find the :trollface: reaction icon ...

**Pull request merged**
