### PR TITLE
filters view on side for baggy

### PR DESCRIPTION
**Pull request by tcitworld**
Follow up of #1402
filter-desktop-sidepanel

Needs css animations. And media queries.

### CODE REVIEW

**Comment by j0k3r** [comment]
Nice one !

**Comment by j0k3r** [comment]
Before merging this one, you should rebase your branch against mine.

**Comment by nicosomb** [comment]
Hi @tcitworld! Do you still have work on this PR?

**Comment by tcitworld** [comment]
It's ready to be used, but quite ugly. I'll see what I can do soon.

**Pull request merged**
