### PR TITLE
Handling socials links into a config file

### PR DESCRIPTION
**Pull request by Simounet**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| Fixed tickets |
| License       | MIT

Hi there,
I'm not sure would merge this but at the time I did these changes, social links URLs were wrong and I thought it might be a good idea to mutualize these informations.

### CODE REVIEW

**Comment by tcitworld** [comment]
Thanks. The new Chrome extension for v2 is at https://chrome.google.com/webstore/detail/wallabagit/peehlcgckcnclnjlndmoddifcicdnabm (it was [changed](https://github.com/wallabag/wallabag/pull/2185) inside wallabag a few weeks ago)

**Comment by tcitworld** [comment]
Can you run `php-cs-fixer` on your changes too please ?

**Comment by Simounet** [comment]
Done.

**Comment by j0k3r** [comment]
Looking good to me, thanks ! :+1:

**Pull request merged**
