### PR TITLE
Remove Flattr references

### PR DESCRIPTION
**Pull request by nicosomb**
As we don't want to use this service (they changed their website, we lost features, etc.), I think it's better to remove flattr into our application.

### CODE REVIEW

**Comment by tcitworld** [comment]
If their API still works, I don't think we should remove it, as a non negligible number of users may still use it. We'll move it at a plugin when it will be possible.

**Comment by j0k3r** [comment]
So, do we remove it?

**Comment by nicosomb** [comment]
> If their API still works

I don't really know what they changed ... I don't know if their API still works.

**Comment by nicosomb** [comment]
I only removed flattr references on about page.

**Comment by j0k3r** [comment]
You can also remove `flattr_url` from `app/config/config.yml`

**Pull request merged**
